// Cloudflare Worker — ombreeluci.it redirect handler
// Rule B: /YYYY/MM/DD/slug/ → /slug/  (15582 redirects via regex)
// Rule C+D: lookup table  (1001 redirects)

const REDIRECTS = {
  // Slug WP → slug Directus (pipeline AI genera slug diverso da WP originale)
  "/it/interpretazioni-disabilita-al-far-east-festival/": "/it/interpretare-la-disabilita-al-far-east-festival/",
  // Numeri rivista rinominati dopo import (INS-3x con doppio trattino → ID corretto)
  "/it/archivio/ins--2/": "/it/archivio/ins-31/",
  "/it/archivio/ins--3/": "/it/archivio/ins-32/",
  "/ombre-e-luci-n-1-1983-sfogliabile/": "/it/ombre-e-luci-n-3-1983-sfogliabile/",
  "/ombre-e-luci-n-1-1983/": "/it/ombre-e-luci-n-3-1983-sfogliabile/",
  "/editoriale-4-la-sindrome-down/": "/it/editoriale-4-il-mio-bambino-con-la-sindrome-down/",
  "/centro-di-formazione-professionale-dell-opera-francescana-charitas-di-vicenza/": "/it/vicenza-centro-di-formazione-professionale-dell-opera-francescana-charitas/",
  "/dialogo-aperto-n-2/": "/it/dialogo-aperto-numero-2/",
  "/nessun-uomo-e-una-pietr/": "/it/nessun-uomo-e-una-pietra/",
  "/e-sempre-stato-rifiutato__trashed/": "/it/e-sempre-stato-rifiutato/",
  "/il-bambino-trisomico/": "/it/trisomia-21-la-sindrome-down/",
  "/chiediamo-alle-comunita-religiose/": "/it/secondo-le-possibilita-e-secondo-il-vangelo-chiediamo-alle-comunita-religiose/",
  "/la-riabilitazione/": "/it/la-riabilitazione-nella-scuole-ma-la-bambina-non-e-tenuta-in-classe/",
  "/psicosi-precoci/": "/it/psicosi-precoci-che-cosa-sono/",
  "/un-centro-per-la-cura-della-psicosi/": "/it/oltre-la-scienza-umanita-e-buon-senso-in-un-centro-per-la-cura-della-psicosi/",
  "/oltre-la-scienza-e-l-umanita-un-centro-per-la-cura-della-psicosi/": "/it/oltre-la-scienza-umanita-e-buon-senso-in-un-centro-per-la-cura-della-psicosi/",
  "/consigli-utili/": "/it/psicosi-infantile-alcuni-consigli-utili/",
  "/una-verita-difficile-a-dirsi/": "/it/integrazione-a-scuola-una-verita-difficile-a-dirsi/",
  "/il-volontariato/": "/it/quando-e-volontariato/",
  "/storia-di-unadozione/": "/it/il-nostro-cucciolo-di-due-metri-storia-di-un-adozione/",
  "/dialogo-aperto/": "/it/dialogo-aperto-n-9/",
  "/dialogo-aperto-n-10/": "/it/dialogo-aperto-n-9/",
  "/e_gli_altri-_figli_consigli_per_-i_-genitori_di_bambino_disabile/": "/it/altri_figli_consigli_per_genitori_bambino_disabile/",
  "/un-piccolo-vademecum-comportarsi-fratelli-le-sorelle/": "/it/altri_figli_consigli_per_genitori_bambino_disabile/",
  "/ma-dopo-rincontro-non-li-vedo-piu/": "/it/ma-dopo-l-incontro-non-li-vedo-piu/",
  "/mio-e-fra-tello-era-handicappato/": "/it/mio-fratello-era-handicappato/",
  "/mi-saro-unidea/": "/it/mi-saro-fatto-un-idea/",
  "/essere-vicini-fin-vita/": "/it/essere-vicini-a-chi-e-in-fin-di-vita/",
  "/un-mondo-scoprire-camminando-fermandoci-2/": "/it/un-mondo-scoprire-camminando-fermandoci/",
  "/prepariamolo-vivere-gli-altri/": "/it/prepariamolo-vivere-con-gli-altri/",
  "/メリークリスマス/": "/it/natale-giappone/",
  "/feliz-natal/": "/it/natale-brasile/",
  "/dialogo-aperto-n-11/": "/it/dialogo-aperto-n-13/",
  "/c-poждеctbom/": "/it/natale-russia/",
  "/sretan-bozi/": "/it/natale-slovenia/",
  "/la-sfida-dellarca-2/": "/it/la-sfida-dellarca-recensione/",
  "/voi-che-avreste-fatto/": "/it/il-peso-degli-sguardi/",
  "/le-parole-martini/": "/it/i-genitori-commentano-le-parole-del-cardinal-martini/",
  "/perche-venuti-ad-assisi/": "/it/siamo-venuti-ad-assisi-per/",
  "/grazie-san-francesco-venuto-camminare/": "/it/grazie-san-francesco-venuto-camminare-con-noi/",
  "/signore-uno-strumento-della-tua-pace/": "/it/signore-fa-di-me-uno-strumento-della-tua-pace/",
  "/lettera-di-una-mamma/": "/it/la-fortuna-di-avere-daniela-lettera-di-una-mamma/",
  "/tutto-quello-che-ha-f/": "/it/tutto-quello-che-ha-fatto-per-noi/",
  "/convento-seconda-famiglia-giampiero/": "/it/convento-una-seconda-famiglia-per-giampiero/",
  "/arrivano-fatt-curagg/": "/it/quando-arrivano-fatti-coraggio/",
  "/numero-17-adulti-sfogliabile/": "/it/ombre-luci-n-17-1987-sfogliabile/",
  "/numero-17-1987-sfogliabile/": "/it/ombre-luci-n-17-1987-sfogliabile/",
  "/ombre-e-luci-n-18-1987-sfogliabile/": "/it/ombre-luci-n-18-1987-sfogliabile/",
  "/numero-18-1987-sfogliabile/": "/it/ombre-luci-n-18-1987-sfogliabile/",
  "/numero-16-1986-sfogliabile/": "/it/ombre-luci-n-16-1986-sfogliabile/",
  "/ombre-luci-n-14-1986-sfogliabile-2/": "/it/ombre-luci-n-14-1986-sfogliabile/",
  "/ombre-luci-n-11-1986-sfogliabile/": "/it/ombre-luci-n-11-1985-sfogliabile/",
  "/non-so-dirlo/": "/it/non-so-come-ne-a-chi-dirlo/",
  "/dal-diario-uninsegnante/": "/it/dal-diario-di-un-insegnante/",
  "/pietre-paragone/": "/it/la-persona-con-disabilita-come-fonte-di-unita-nella-chiesa/",
  "/dove-vivono-come-vivono/": "/it/villa-san-giovanni-di-dio/",
  "/vivono-vivono-le-persone-colpite-malattia-mentale/": "/it/dove-come-vivono-persone-colpite-malattia-mentale/",
  "/boccati-nel-sogno/": "/it/bloccati-nel-sogno/",
  "/scuola-ricamo-stare-insieme-divertendoci/": "/it/scuola-ricamo-imparare-divertendoci/",
  "/fare-teatro/": "/it/fare-teatro-persone-disabili/",
  "/dialogo-aperto-m-24/": "/it/dialogo-aperto-n-24/",
  "/conoscere-lhandicap-autismo/": "/it/conoscere-handicap-autismo/",
  "/sotto-rocchio-dellorologio/": "/it/christopher-nolan-sotto-locchio-dellorologio/",
  "/ascolta-bone-joseph/": "/it/ascolta-bene-joseph/",
  "/rimini-ex-mattatoio-riqualificato-a-centro-di-accoglienza-per-disabilita/": "/it/riccione-ex-mattatoio-riqualificato-a-centro-di-accoglienza-per-disabilita/",
  "/una-grande-famiglia-del-mondo/": "/it/fede-e-luce-una-grande-famiglia-del-mondo/",
  "/un-campeggio-rocca-papa-ora-comincia-bello/": "/it/vita-fede-e-luce-n-11-un-campeggio-rocca-papa-ora-comincia-bello/",
  "/incontro-internazionale-edimburgo-1-9-agosto-1990/": "/it/incontro-internazionale-edimburgo-agosto-1990/",
  "/malattia-mentale-e-legge/": "/it/malattia-mentale-legge-180/",
  "/un-territorio-molti-progetti/": "/it/primavalle-un-territorio-molti-progetti/",
  "/se/": "/it/anche-noi-siamo-persone/",
  "/diaolog/": "/it/dialogo-aperto-n-35/",
  "/treviso-in-your-shoes-il-concorso-studentesco-per-progetti-di-inclusione-sociale/": "/it/in-your-shoes-concorso-studenti-inclusione/",
  "/piu-che-una-rivista-una-grande-famiglia/": "/it/10-anni-di-ombre-e-luci-piu-che-una-rivista-una-grande-famiglia/",
  "/unestate-di-campi-fede-e-luce-2/": "/it/ridere-a-partire-dal-corpo/",
  "/non-si-puo-ridere-che-dellhandicap-2/": "/it/ridere-a-partire-dal-corpo/",
  "/la-sedia-a-rotelle-e-i-chicchi-duva-2/": "/it/ridere-a-partire-dal-corpo/",
  "/dalle-province-n-127-2/": "/it/ridere-a-partire-dal-corpo/",
  "/un-panorama-da-riscoprire/": "/it/ridere-a-partire-dal-corpo/",
  "/un-gettone-di-liberta/": "/it/ridere-a-partire-dal-corpo/",
  "/un-gettone-di-liberta-recensione-2/": "/it/ridere-a-partire-dal-corpo/",
  "/ridere-a-partire-dal-corpo-2/": "/it/un-dado-vegetale-da-sogno-e-fatto-in-casa/",
  "/un-gettone-di-liberta-2/": "/it/mio-figlio-luciano/",
  "/la-nostra-vita-insieme-recensione-2/": "/it/mio-figlio-luciano/",
  "/di-padre-in-figlio-conversazioni-sul-rischio-di-educare-recensione-2/": "/it/mio-figlio-luciano/",
  "/dialogo-aperto-n-127-2/": "/it/mio-figlio-luciano/",
  "/la-carrozzina-sulle-macerie-2/": "/it/mio-figlio-luciano/",
  "/umorismo-e-handicap-un-terreno-minato-2/": "/it/mio-figlio-luciano/",
  "/ridere-e-una-cosa-seria-2/": "/it/mio-figlio-luciano/",
  "/diritti-delle-persone-disabili/": "/it/diritti-delle-persone-disabili-secondo-onu/",
  "/viola-e-mimosa/": "/it/liberta/",
  "/vite-straordinarie-3/": "/it/liberta/",
  "/dalle-province-n-144-2/": "/it/liberta/",
  "/dialogo-aperto-n-144-2/": "/it/liberta/",
  "/meglio-di-come-ci-si-aspetta-2/": "/it/liberta/",
  "/mi-chiamo-lucia-2/": "/it/liberta/",
  "/anffas-60-anni-di-futuro-2/": "/it/liberta/",
  "/tutti-possono-essere-santi-2/": "/it/liberta/",
  "/casa-loic/": "/it/inaugurazione-casa-loic-scuola-laboratorio-artigianale-per-ragazzi-disabili/",
  "/casa-loic-scuola-laboratorio-artigianale-per-ragazzi-disabili/": "/it/inaugurazione-casa-loic-scuola-laboratorio-artigianale-per-ragazzi-disabili/",
  "/una-mappa-di-ricordi-virtuale-per-contrastare-lalzheimer/": "/it/alzheimer-vita-ricordi/",
  "/diversi-da-chi-diversi-da-chi-normali-vite-con-handicap/": "/it/diversi-da-chi-normali-vite-con-handicap/",
  "/la-nostra-meglio-gioventu-fano-2018/": "/it/fano2018/",
  "/in-alto-in-basso/": "/it/luca-mio-figlio-autistico/",
  "/esperienza-di-un-obiettore-in-una-comunita/": "/it/ho-guadagnato-un-anno-al-carro/",
  "/vestita-di-nuvole2/": "/it/vestita-di-nuvole/",
  "/bozza-automatica/": "/it/catechesi-anche-per-le-persone-autistiche/",
  "/insieme-si-puo/": "/it/soluzione-per-malati-mentali-insieme-si-puo/",
  "/la-nostra-casa/": "/it/comunita-tau-la-nostra-casa/",
  "/comunita-taula-nostra-casa/": "/it/comunita-tau-la-nostra-casa/",
  "/il-mio-piede-sinistro-2/": "/it/il-mio-piede-sinistro-il-film/",
  "/rain-man/": "/it/rain-man-la-recensione/",
  "/figli-di-un-dio-minore/": "/it/figli-di-un-dio-minore-recensione/",
  "/come-dirlo-2/": "/it/il-progetto-girotondo/",
  "/non-era-normale-2/": "/it/il-mistero-di-tanto-bene/",
  "/laltra-famiglia-storie-e-percorsi-di-affido-al-villaggio-sos-recensione/": "/it/viola-e-mimosa-a-manila/",
  "/io-sono-qui-recensione-2/": "/it/viola-e-mimosa-a-manila/",
  "/mai-piu-soli-lavventura-di-fede-e-luce-recensione-2/": "/it/viola-e-mimosa-a-manila/",
  "/fede-e-luce-dalle-province-n-121-2/": "/it/viola-e-mimosa-a-manila/",
  "/da-citta-del-messico/": "/it/viola-e-mimosa-a-manila/",
  "/viola-e-mimosa-da-citta-del-messico-2/": "/it/viola-e-mimosa-a-manila/",
  "/dialogo-aperto-n-121-2/": "/it/viola-e-mimosa-a-manila/",
  "/un-po-di-follia-per-fare-meraviglie-2/": "/it/viola-e-mimosa-a-manila/",
  "/per-una-vita-di-comunione-2/": "/it/viola-e-mimosa-a-manila/",
  "/jean-christophe-parisot-un-cercatore-di-dio-2/": "/it/viola-e-mimosa-a-manila/",
  "/bartimeo-uomo-solo-in-mezzo-alla-folla-2/": "/it/viola-e-mimosa-a-manila/",
  "/qualcuno-aspetta-2/": "/it/viola-e-mimosa-a-manila/",
  "/una-comunita-e-essere-insieme-2/": "/it/viola-e-mimosa-a-manila/",
  "/primavera-di-fede-2/": "/it/viola-e-mimosa-a-manila/",
  "/prendetene-e-mangiatene-tutti-2/": "/it/viola-e-mimosa-a-manila/",
  "/intervista-a-jean-vanier-2/": "/it/viola-e-mimosa-a-manila/",
  "/cosi-e-sceso-dal-trono-2/": "/it/viola-e-mimosa-a-manila/",
  "/io-sono-nato-cosi-come-imparare-a-guardare-oltre-la-differenza-recensione-2/": "/it/viola-e-mimosa-a-manila/",
  "/come-pinguini-nel-deserto-recensione-2/": "/it/viola-e-mimosa-a-manila/",
  "/una-notte-ho-sognato-che-parlavi-recensione-2/": "/it/viola-e-mimosa-a-manila/",
  "/carissimo-cardinale-2/": "/it/viola-e-mimosa-a-manila/",
  "/la-figlia-dellaltra-recensione-2/": "/it/viola-e-mimosa-a-manila/",
  "/il-vangelo-dei-vinti-recensione-2/": "/it/viola-e-mimosa-a-manila/",
  "/annachiara-bortolotti-ed-curcu-genovese-pp-125/": "/it/viola-e-mimosa-a-manila/",
  "/chiamami-alex-recensione-2/": "/it/viola-e-mimosa-a-manila/",
  "/momenti-misteriosi-2/": "/it/il-carro-una-casa-famiglia-per-tutti/",
  "/quando-a-raccontare-lolocausto-sono-gli-ex-naxisti/": "/it/recensione-final-account/",
  "/disabilita-e-quei-bisogni-non-ascoltati/": "/it/recensione-listen/",
  "/come-difficile-convivere-con-lepatite-b/": "/it/recensione-the-best-is-yet-to-come/",
  "/perso-nella-traduzione/": "/it/recensione-quo-vadis-aida/",
  "/oaza-ai-confini-della-finzione/": "/it/recensione-oaza/",
  "/barriere-invisibili-al-cuore-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/mi-saro-fatto-unidea-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/fede-e-luce-essere-movimento-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/proprio-io-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/un-tesoro-inestimabile-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/il-dono-dellunita-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/custodire-ogni-persona-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/la-poverta-delle-beatitudini-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/una-profezia-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/e-ci-si-sente-un-po-soli-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/tutti-insieme-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/fragile-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/la-scossa-della-vunerabilita-2/": "/it/mai-piu-soli-tre-testimonianze/",
  "/programma-del-pellegrinaggio-a-roma-del-1975-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/perche-questo-pellegrinaggio-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/bilancio-fede-e-luce-1975-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/i-piu-difficili-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/mi-sento-in-crisi-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/festa-della-luce-1976-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/pennellate-dai-centri-fede-e-luce-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/incontrarsi-il-venerdi-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/resoconto-della-riunione-internazionale-di-fede-e-luce-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/vedremo-mai-la-luce-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/ci-hanno-scritto-3/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/esperienze-un-week-end-fuori-dallordinario-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/dove-lo-prendo-tanto-amore-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/xavier-un-mio-un-nostro-nuovo-a-amico-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/un-metodo-efficace-per-leducazione-dei-bambini-con-disabilita-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/guidare-alla-luce-catechesi-sensoriale-per-una-vita-spirituale-inclusiva-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/letture-consigliate-darti-la-vita-recensione-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/notiziario-fede-e-luce-il-resoconto-dellultima-festa-della-luce-e-altre-notizie-dal-movimento-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/alla-ricerca-delle-vere-vacanze-rompere-gli-schemi-e-scoprire-il-significato-profondo-del-riposo-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/la-vecchia-signora-brontolona-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/i-bambini-autistici-una-guida-per-genitori-recensione-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/a-tutti-i-gruppi-fede-e-luce-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/notiziario-fede-e-luce-dicembre-1977/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/esperienze-estive-fra-arche-e-mary-mount-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/alfedena-1976-esperienze-di-vita-comunitaria-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/attivita-di-tempo-libero-e-vita-comunitaria-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/per-la-nostra-riflessione-una-croce-di-carta-smerigliata-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/ci-hanno-scritto-n-11-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/lettera-aperta-a-padre-michel-charpantier-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/editoriale-parliamo-di-insieme-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/bilancio-fede-e-luce-1976-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/gli-altri-un-figlio-subnormale-recensione-libro-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/notiziario-fede-e-luce-n-13-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/fede-e-luce-incontri-internazionali-e-nazionali-1977-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/esperienze-al-club-avance-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/techniche-di-recupero-per-i-disabili-gravi-la-socializzazione-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/per-nostra-riflessione-la-comunione-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/ci-hanno-scritto-n-13-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/editoriale-auguri-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/letture-consigliate-n-13-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/parliamo-di-ri-educazione-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/notiziario-fede-e-luce-n-14-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/attivita-di-fine-stagione-del-gruppo-san-paolo-di-roma-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/cosa-si-fa-nelle-casette-di-fede-e-luce-le-risposte-di-chi-ce-stato-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/leducazione-delle-persone-disabili-imparare-a-vestirsi-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/per-la-nostra-riflessione-milano-vederci-piu-chiaro/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/inno-alla-vita-di-una-handicappata-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/ci-hanno-scritto-n-14-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/editoriale-vacanze-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/editoriale-amici-o-fratelli-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/editoriale-le-nostre-paure-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/ci-hanno-scritto-n-16-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/la-comunita-che-accoglie-di-rifiutati-recensione-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/preparazione-al-pellegrinaggio-fede-e-luce-ad-assisi-1978-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/quando-arrivano-le-vacanze-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/ci-hanno-scritto-n-18-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/ci-hanno-scritto-n-19-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/quattordici-anni-con-loro-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/per-la-loro-educazione-bilancio-di-unestate-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/alfedena-1978-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/vacanze-1978-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/una-lezione-damore-incontro-fede-e-luce-llalelli-galles-del-sud-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/soggiorno-allarche-1978-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/sono-andata-a-bruxelles-a-fare-volontariato-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/katimavik-una-parole-escquimese-che-vuol-dire-incontro/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/katimavik-una-parola-escquimese-che-vuol-dire-incontro-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/i-bambini-profondamente-handicappati-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/lamore-non-basta-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/aria-di-vacanze-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/ci-hanno-scritto-n-22-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/un-compleanno-al-capezzale-di-un-amico-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/mattone-su-mattone-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/focus-gli-adulti-profondamente-handicappati-alcune-testimonianze-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/mio-fratello-marco-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/siamo-stati-dei-buoni-genitori-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/non-avrei-mai-pensato-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/un-antidoto-alla-disperazione-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/sprovveduto-e-sorpreso-chi-non-lo-e-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/incontro-internazionale-a-cuneo-28-29-aprile-1979-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/pellegrinaggio-a-loreto-18-20-maggio-1979/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/pellegrinaggio-a-loreto-1979-raccontato-da-olga-gammarelli/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/perche-vi-chiamate-fede-e-luce-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/ci-hanno-scritto-n-23-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/gli-adulti-lievemente-handicappati/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/trovai-lavoro-in-una-casa-farmaceutica-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/amicizie-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/vuoi-essere-mio-amico-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/saluta-la-tua-insegnante-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/e-domani-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/dialoghi-scomodi-amicizie-vere-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/teresa-2/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/teresa-ventanni-di-cambiamenti-nellapproccio-alla-disabilita/": "/it/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi/",
  "/genitori-speciali-zzati-servizio-di-consulenza-pedagogica-di-trento-2/": "/it/qualcosa-e-cambiato/",
  "/gioia-e-le-altre/": "/it/qualcosa-e-cambiato/",
  "/gioia-e-le-altre-recensione-2/": "/it/qualcosa-e-cambiato/",
  "/il-chicco-recensione-2/": "/it/qualcosa-e-cambiato/",
  "/alla-ricerca-di-dory-recensione-2/": "/it/qualcosa-e-cambiato/",
  "/la-tempesta-di-sasa-recensione-2/": "/it/qualcosa-e-cambiato/",
  "/se-arianna-recensione-2/": "/it/qualcosa-e-cambiato/",
  "/viola-e-occhiolino-2/": "/it/qualcosa-e-cambiato/",
  "/il-valore-del-cammino-insieme-2/": "/it/qualcosa-e-cambiato/",
  "/nuove-comunita-fede-e-luce-festa-in-umbria-2/": "/it/qualcosa-e-cambiato/",
  "/accogliere-la-sorpresa-2/": "/it/qualcosa-e-cambiato/",
  "/il-messaggio-del-giubileo-dialogo-con-mons-rino-fisichella-2/": "/it/qualcosa-e-cambiato/",
  "/pedagogia-del-dolore-innocente-recensione-2/": "/it/qualcosa-e-cambiato/",
  "/io-sono-con-te-recensione-2/": "/it/qualcosa-e-cambiato/",
  "/dalle-province-n-136-2/": "/it/qualcosa-e-cambiato/",
  "/i-doni-di-dio-2/": "/it/qualcosa-e-cambiato/",
  "/leducazione-attraverso-lesempio-2/": "/it/qualcosa-e-cambiato/",
  "/la-misericordia-2/": "/it/qualcosa-e-cambiato/",
  "/tu-ci-hai-chiamati-eccoci-2/": "/it/qualcosa-e-cambiato/",
  "/lamicizia-incarnata-2/": "/it/eccomi-lesempio-di-maria/",
  "/joyeux-noel-3/": "/it/eccomi-lesempio-di-maria/",
  "/sempre-di-nuovo-ci-commuove-2/": "/it/eccomi-lesempio-di-maria/",
  "/dialogo-aperto-n-124-2/": "/it/eccomi-lesempio-di-maria/",
  "/la-bambina-che-andava-a-pile/": "/it/la-mia-forza-nella-mia-differenza/",
  "/la-bambina-che-andava-a-pile-recensione-2/": "/it/la-mia-forza-nella-mia-differenza/",
  "/dalle-provice-n-142/": "/it/la-mia-forza-nella-mia-differenza/",
  "/dalle-province-n-142-2/": "/it/la-mia-forza-nella-mia-differenza/",
  "/dalle-mamme-di-palidoro-perche-curare-non-significa-solo-guarire-2/": "/it/la-mia-forza-nella-mia-differenza/",
  "/limportante-e-che-sia-sano-2/": "/it/dimmi-chi-ammiri/",
  "/raccontami-il-mare-che-hai-dentro-vivere-con-un-figlio-autistico-recensione-2/": "/it/dimmi-chi-ammiri/",
  "/quello-che-non-ho-mai-detto-e-lisola-di-noi-recensione-di-due-libri-di-federico-de-rosa-2/": "/it/dimmi-chi-ammiri/",
  "/diaologo-aperto-n-140-2/": "/it/dimmi-chi-ammiri/",
  "/epigenetica-e-malattie-psichiatriche-2/": "/it/dimmi-chi-ammiri/",
  "/mi-chiamo-charlotte-fien-e-ho-la-sindrome-di-down-2/": "/it/dimmi-chi-ammiri/",
  "/non-smettete-di-crederci-mai-recensione-2/": "/it/dalle-province-n-123/",
  "/persone-prima-che-disabili-una-riflessione-sullhandicap-tra-giustizia-ed-etica-recensione-2/": "/it/dalle-province-n-123/",
  "/un-dio-inutile-recensione-2/": "/it/dalle-province-n-123/",
  "/cosa-fare-delle-nostre-ferite-recensione-2/": "/it/dalle-province-n-123/",
  "/creatures-disconforts-2/": "/it/dalle-province-n-123/",
  "/sia-fatta-la-tua-volonta-2/": "/it/ci-hanno-scritto-insieme-n-27/",
  "/di-nuovo-in-cammino-2/": "/it/ci-hanno-scritto-insieme-n-27/",
  "/fratelli-e-sorelle-di-persone-con-disabilita-3/": "/it/ci-hanno-scritto-insieme-n-27/",
  "/uno-due-tre-stella-2/": "/it/ci-hanno-scritto-insieme-n-27/",
  "/quel-che-la-convenzione-dice-e-non-dice/": "/it/intervista-giampiero-griffo/",
  "/una-storia-sacra-2/": "/it/le-mimose-di-yolanda/",
  "/speciale-natale-nel-mondo-2/": "/it/le-mimose-di-yolanda/",
  "/posso-devo-voglio-2/": "/it/la-nostra-scelta-di-cristina/",
  "/volevo-essere-una-farfalla-recensione-2/": "/it/la-nostra-scelta-di-cristina/",
  "/dalle-province-2/": "/it/la-nostra-scelta-di-cristina/",
  "/speleologi-del-mistero-del-piccolo-2/": "/it/la-nostra-scelta-di-cristina/",
  "/la-parola-alle-mamme-2/": "/it/la-nostra-scelta-di-cristina/",
  "/anoressia-fame-damore-e-2/": "/it/la-nostra-scelta-di-cristina/",
  "/i-tuoi-figli-2/": "/it/la-nostra-scelta-di-cristina/",
  "/si-chiama-sara-2/": "/it/la-nostra-scelta-di-cristina/",
  "/la-nostra-scelta/": "/it/la-nostra-scelta-di-cristina/",
  "/mio-figlio-luciano-2/": "/it/il-lato-b-di-essere-papa-di-un-figlio-disabile/",
  "/sara-e-le-sbiruline-di-emily-2/": "/it/bellezza-e-handicap/",
  "/il-vecchio-re-nel-suo-esilio/": "/it/bellezza-e-handicap/",
  "/dialogo-aperto-n-119-2/": "/it/bellezza-e-handicap/",
  "/come-essere-vicini-allaltro-2/": "/it/bellezza-e-handicap/",
  "/i-nonni-una-tenerezza-in-piu-2/": "/it/bellezza-e-handicap/",
  "/il-loro-sguardo-buca-le-nostre-ombre-recensione-2/": "/it/bellezza-e-handicap/",
  "/larca-di-trosly-2/": "/it/bellezza-e-handicap/",
  "/sindrome-di-costello-la-storia-di-sandrino-2/": "/it/bellezza-e-handicap/",
  "/affrontare-lenorme-paura-intervista-a-pietro-2/": "/it/bellezza-e-handicap/",
  "/cosa-sono-le-malattie-rare-2/": "/it/bellezza-e-handicap/",
  "/rarina-storia-di-un-fiore-raro-2/": "/it/bellezza-e-handicap/",
  "/dialogo-aperto-n-118-2/": "/it/bellezza-e-handicap/",
  "/carissime-mamme-2/": "/it/bellezza-e-handicap/",
  "/mani-calde-recensione-2/": "/it/bellezza-e-handicap/",
  "/fai-bei-sogni-recensione-2/": "/it/bellezza-e-handicap/",
  "/fede-e-luce-dalle-provincie-2/": "/it/bellezza-e-handicap/",
  "/fede-e-luce-una-fedelta-che-ridona-lentusiasmo-2/": "/it/bellezza-e-handicap/",
  "/jean-vanier-dalla-palestina-2/": "/it/bellezza-e-handicap/",
  "/mamma-sono-contento-di-essere-nato-2/": "/it/bellezza-e-handicap/",
  "/la-memoria-del-bello-2/": "/it/bellezza-e-handicap/",
  "/falsi-moralismi-sul-bello-di-essere-down-2/": "/it/bellezza-e-handicap/",
  "/cosa-rende-qualcuno-straordinario-intervista-a-nick-vujicic-2/": "/it/bellezza-e-handicap/",
  "/un-gatto-la-comunita-e-il-nostro-apartheid/": "/it/luca-adotta-alba/",
  "/una-sera-a-roma-allo-stadio-dei-marmi-per-lapertura-delle-special-olympics/": "/it/una-sera-a-roma-stadio-dei-marmi-special-olympics/",
  "/dialogo-aperto-n-116-2/": "/it/giovani-eroi/",
  "/vita-fede-e-luce-n-113-2/": "/it/giovani-eroi/",
  "/fede-e-luce-festeggia-i-suoi-40-anni-1971-2011/": "/it/giovani-eroi/",
  "/vita-fede-e-luce-la-festa-per-i-nostri-40-anni-1971-2011-2/": "/it/giovani-eroi/",
  "/fede-e-luce-e-subito-scatto-la-molla-2/": "/it/giovani-eroi/",
  "/10-buoni-motivi-per-fare-volontariato-2/": "/it/giovani-eroi/",
  "/doposcuola-al-campo-rom-2/": "/it/giovani-eroi/",
  "/lamicizia-asimmetrica-2/": "/it/giovani-eroi/",
  "/volontariato-una-leva-per-la-vita-2/": "/it/giovani-eroi/",
  "/oggi-sono-libero-2/": "/it/giovani-eroi/",
  "/un-sacco-di-felicita-2/": "/it/giovani-eroi/",
  "/ndangwini-casa-dove-esiste-una-famiglia-2/": "/it/giovani-eroi/",
  "/tra-individualismo-e-impegno-i-giovani-hanno-bisogno-di-concretezza-2/": "/it/giovani-eroi/",
  "/istantanea-2/": "/it/giovani-eroi/",
  "/nessun-profitto-recensione-2/": "/it/giovani-eroi/",
  "/il-linguaggio-segreto-dei-fiori-recensione-2/": "/it/giovani-eroi/",
  "/la-speranza-non-fa-rumore-recensione-2/": "/it/giovani-eroi/",
  "/per-sempre-recensione-2/": "/it/giovani-eroi/",
  "/in-corsia-2/": "/it/giovani-eroi/",
  "/vita-fede-e-luce-linizio-di-un-cammino-2/": "/it/giovani-eroi/",
  "/posso-vivere-lssenziale-che-non-e-fare-per-ma-vivere-con-le-persone-piu-fragili-2/": "/it/giovani-eroi/",
  "/farsi-carico-degli-ultimi-2/": "/it/giovani-eroi/",
  "/dialogo-aperto-n-115-2/": "/it/giovani-eroi/",
  "/quasi-non-li-riconoscevo-2/": "/it/giovani-eroi/",
  "/tempo-di-regali-2/": "/it/giovani-eroi/",
  "/vizi-e-virtu-del-vivere-recensione-2/": "/it/giovani-eroi/",
  "/storia-di-un-uomo-ritratto-di-carlo-maria-martini-recensione-2/": "/it/giovani-eroi/",
  "/avevano-spento-anche-la-luna-recensione-2/": "/it/giovani-eroi/",
  "/il-tempo-delle-donne-recensione-2/": "/it/giovani-eroi/",
  "/con-lidea-di-non-andare-2/": "/it/giovani-eroi/",
  "/tre-domande-ed-un-pellegrinaggio-2/": "/it/giovani-eroi/",
  "/messaggeri-di-gioia-2/": "/it/giovani-eroi/",
  "/nel-profondo-della-malattia-una-comunione-e-possibile-2/": "/it/giovani-eroi/",
  "/ci-chiedono-da-che-parte-stai-2/": "/it/giovani-eroi/",
  "/la-grande-casa-di-peter-pan-2/": "/it/giovani-eroi/",
  "/allora-hai-deciso-2/": "/it/insegnante-di-lettere-canale-della-vita/",
  "/il-carro-una-casa-famiglia-per-tutti-2/": "/it/insegnante-di-lettere-canale-della-vita/",
  "/relazioni-sincere-2/": "/it/insegnante-di-lettere-canale-della-vita/",
  "/posso-salutare-la-mamma-2/": "/it/insegnante-di-lettere-canale-della-vita/",
  "/purche-2/": "/it/insegnante-di-lettere-canale-della-vita/",
  "/come-e-nato-ombre-e-luci-2/": "/it/insegnante-di-lettere-canale-della-vita/",
  "/chi-ha-seminato-nelle-lacrime-miete-nella-gioia-2/": "/it/insegnante-di-lettere-canale-della-vita/",
  "/molto-lavoro-da-fare-2/": "/it/insegnante-di-lettere-canale-della-vita/",
  "/sicurezza-nel-cammino-2/": "/it/insegnante-di-lettere-canale-della-vita/",
  "/effetto-alfedena-2/": "/it/insegnante-di-lettere-canale-della-vita/",
  "/una-scelta-difficile/": "/it/dopo-la-scuola-dellobbligo-una-scelta-difficile/",
  "/circa-il-concetto-di-apertura-dei-centri-diurni-riabilitativi/": "/it/centri-diurni-coronavirus/",
  "/ci-provero-2/": "/it/vuoi-bene-a-gesu/",
  "/pregando-su-una-sedia-imponente-e-semplice-2/": "/it/vuoi-bene-a-gesu/",
  "/il-mosaico-tanti-sassolini-colorati-2/": "/it/vuoi-bene-a-gesu/",
  "/mariangela-linizio-a-santa-silvia-2/": "/it/vuoi-bene-a-gesu/",
  "/partecipe-dei-miracoli-2/": "/it/vuoi-bene-a-gesu/",
  "/mirtilli-2/": "/it/vuoi-bene-a-gesu/",
  "/small-talk-ma-extralarge-2/": "/it/vuoi-bene-a-gesu/",
  "/il-regalo-piu-bello-2/": "/it/vuoi-bene-a-gesu/",
  "/quel-gesto-2/": "/it/vuoi-bene-a-gesu/",
  "/quanta-forza-2/": "/it/vuoi-bene-a-gesu/",
  "/un-patrimonio-profuso-a-piene-mani-2/": "/it/vuoi-bene-a-gesu/",
  "/sollecitare-la-speranza-2/": "/it/vuoi-bene-a-gesu/",
  "/piero-e-il-bruco-farfalla-recensione-2/": "/it/giubileo-2016-la-vera-gioia/",
  "/dalle-provincie-n-134-2/": "/it/giubileo-2016-la-vera-gioia/",
  "/la-passione-della-pazienza-2/": "/it/giubileo-2016-la-vera-gioia/",
  "/un-laboratorio-creativo-a-pantigliate-2/": "/it/giubileo-2016-la-vera-gioia/",
  "/il-chicco-vivere-il-vangelo-in-azione-2/": "/it/giubileo-2016-la-vera-gioia/",
  "/papa-francesco-al-chicco-qui-mi-avete-toccato-il-cuore-2/": "/it/giubileo-2016-la-vera-gioia/",
  "/oltre-il-limite-2/": "/it/giubileo-2016-la-vera-gioia/",
  "/perche-di-katherine-e-nerissa-non-ci-sono-tracce/": "/it/the-crown-cugine-autismo/",
  "/dalle-province-n-140-2/": "/it/dopo-di-noi-i-diritti-che-ci-sono/",
  "/legge-sul-dopo-di-noi-issiamo-le-vele-2/": "/it/dopo-di-noi-i-diritti-che-ci-sono/",
  "/come-e-stato-possibile-tutto-questo-2/": "/it/doni-preziosi/",
  "/alza-lo-sguardo/": "/it/doni-preziosi/",
  "/per-me-e-felicita-2/": "/it/doni-preziosi/",
  "/mai-piu-soli-tre-testimonianze-2/": "/it/la-covazione-di-un-papa/",
  "/mamma-ti-posso-parlare-recensione/": "/it/rico-oscar-e-il-ladro-ombra-recensione/",
  "/chi-resta-deve-capire-recensione-2/": "/it/rico-oscar-e-il-ladro-ombra-recensione/",
  "/dedicato-ad-unamica-2/": "/it/a-te-bambino-mio/",
  "/questestate-faremo-2/": "/it/a-te-bambino-mio/",
  "/dialogo-aperto-n-136-2/": "/it/quattro-giorni-mano-nella-mano/",
  "/vedere-oltre-finestre-su-una-storia-recensione-2/": "/it/quattro-giorni-mano-nella-mano/",
  "/il-libro-di-charlotte-recensione-2/": "/it/quattro-giorni-mano-nella-mano/",
  "/genitori-recensione-film-2/": "/it/quattro-giorni-mano-nella-mano/",
  "/sono-graditi-visi-sorridenti-recensione-2/": "/it/borderline-recensione/",
  "/riscoprire-cio-che-unisce-i-cuori-di-tutti-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/un-affidamento-speciale-3/": "/it/qualche-raggio-di-sole-in-siria/",
  "/la-ragnatela-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/siblings-recensione-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/lo-zaino-di-emma-recensione-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/alla-fine-qualcosa-ci-inventeremo-che-ne-sara-di-mio-figlio-autistico-quando-non-saro-piu-al-suo-fianco-recensione-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/di-corsa-verso-francesco-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/famiglia-per-chi-famiglia-per-cosa-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/una-buona-scuola-damore-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/la-lampada-dei-desideri-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/pinocchio-teatro-integrato-ma-non-solo-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/luoghi-della-relazione-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/il-libro-di-cristopher-a-wonder-story-recensione-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/osservazioni-di-una-mamma-qualunque-recensione-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/viola-e-il-bullismo-2/": "/it/qualche-raggio-di-sole-in-siria/",
  "/fede-e-luce-in-armenia-e-in-iran/": "/it/30-anni-chicco-dandoci-la-risposta-che-il-cuore-chiedeva/",
  "/un-ragazzo-ribelle-2/": "/it/30-anni-chicco-dandoci-la-risposta-che-il-cuore-chiedeva/",
  "/ziguli-2/": "/it/30-anni-chicco-dandoci-la-risposta-che-il-cuore-chiedeva/",
  "/liguana-non-vuole/": "/it/30-anni-chicco-dandoci-la-risposta-che-il-cuore-chiedeva/",
  "/liguana-non-vuole-recensione-2/": "/it/30-anni-chicco-dandoci-la-risposta-che-il-cuore-chiedeva/",
  "/cosa-ti-manca-per-essere-felice-recensione-2/": "/it/30-anni-chicco-dandoci-la-risposta-che-il-cuore-chiedeva/",
  "/voci-dal-silenzio-recensione-2/": "/it/30-anni-chicco-dandoci-la-risposta-che-il-cuore-chiedeva/",
  "/fede-e-luce-in-iraq-2/": "/it/30-anni-chicco-dandoci-la-risposta-che-il-cuore-chiedeva/",
  "/un-coro-aperto-a-tutti-2/": "/it/il-dilemma-della-valutazione/",
  "/dalle-province-n-123-2/": "/it/il-dilemma-della-valutazione/",
  "/ho-imparato-2/": "/it/aprirsi-ad-altre-famiglie/",
  "/testimoni-dellincontro-2/": "/it/aprirsi-ad-altre-famiglie/",
  "/come-sei-cresciuto-2/": "/it/aprirsi-ad-altre-famiglie/",
  "/tra-lacquario-e-loceano-2/": "/it/voci-di-campo/",
  "/occasioni-per-stare-al-passo-2/": "/it/voci-di-campo/",
  "/aprirsi-ad-altre-famiglie-2/": "/it/voci-di-campo/",
  "/precious-recensione-film-2/": "/it/dialogo-aperto-n-113/",
  "/uildm-unione-italiana-lotta-alla-distrofia-muscolare-2/": "/it/dialogo-aperto-n-113/",
  "/vivere-con-la-distrofia-intervista-a-me-2/": "/it/dialogo-aperto-n-113/",
  "/costruirsi-un-totem-capire-e-sentire-il-proprio-valore-recensione-2/": "/it/e-la-luna-mi-guardo-recensione/",
  "/e-la-luna-mi-guardo-recensione-2/": "/it/vita-fede-e-luce-n-110/",
  "/scegliamo-con-cura-le-parole-2/": "/it/viola-e-mimosa-desaparecida/",
  "/il-mistero-di-tanto-bene-2/": "/it/angelo-un-compagno-di-viaggio/",
  "/raggi-di-sole-2/": "/it/angelo-un-compagno-di-viaggio/",
  "/eh-io-sono-qui-2/": "/it/angelo-un-compagno-di-viaggio/",
  "/90-anni-di-jean-2/": "/it/una-radice-e-delle-ali/",
  "/viola-e-mimosa-desaparecida-2/": "/it/una-radice-e-delle-ali/",
  "/con-il-tuo-passo-percorsi-agesci-2/": "/it/una-radice-e-delle-ali/",
  "/dalle-province-n-142-3/": "/it/dinamiche-fondamentali/",
  "/dinamiche-fondamentali-2/": "/it/i-miei-occhi-e-il-mio-cuore-hanno-vissuto-la-meraviglia/",
  "/quanta-carta-stampata/": "/it/ombre-e-luci-oggi-ha-ancora-senso/",
  "/la-forma-della-voce/": "/it/la-forma-della-voce-recensione/",
  "/io-figlio-di-mio-figlio/": "/it/io-figlio-di-mio-figlio-recensione/",
  "/la-sete-e-lacqua-della-speranza-una-riflessione-di-don-marco-bove/": "/it/la-sete-e-lacqua-della-speranza/",
  "/lettera-aperta-a-francesco-dassisi-2/": "/it/pellegrinaggio-assisi-1978-luis-sankale/",
  "/assisi-1978/": "/it/pellegrinaggio-assisi-1978-luis-sankale/",
  "/oltre-la-cronaca-vicini-al-quotidiano-2/": "/it/scarti-o-pietre-portanti/",
  "/i-miei-occhi-e-il-mio-cuore-hanno-vissuto-la-meraviglia-2/": "/it/scarti-o-pietre-portanti/",
  "/quanti-conosci-per-nome-2/": "/it/cosa-so-dei-social-e-cosa-ne-penso/",
  "/la-comunita-che-accoglie-di-rifiutati-recensione/": "/it/la-comunita-che-accoglie-i-rifiutati-recensione/",
  "/curare-lautismo-a-casa-unopera-damore/": "/it/curare-lautismo-a-casa-un-opera-damore/",
  "/lo-straordinario-viaggio-di-nujeen-recensione-2/": "/it/dialogo-aperto-n-138/",
  "/corridoi-umanitari-2/": "/it/dialogo-aperto-n-138/",
  "/dettagli-inutili-recensione-2/": "/it/dialogo-aperto-n-138/",
  "/dalle-province-n-125-2/": "/it/agli-antipodi-dellindividualismo/",
  "/fede-e-luce-in-terra-santa-2/": "/it/agli-antipodi-dellindividualismo/",
  "/disabili-e-trapianti/": "/it/sempre-damigella-mai-sposa/",
  "/agli-antipodi-dellindividualismo-2/": "/it/un-gioco-da-fare-quando-fuori-piove/",
  "/editoriale-italiana-2000-pp-670/": "/it/itinerari-guida-annuario-accoglienza-cattolica-italia-2000-recensione/",
  "/ci-hanno-scritto-una-critica-allultimo-numero-di-insieme-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/per-la-nostra-riflessione-prendete-e-mangiatene-tutti-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/leducazione-dei-bambini-cosiddetti-lievi-si-ma-quale-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/viviamo-una-vita-normale-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/non-e-cosi-facile-essere-madre-di-una-bambina-non-grave-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/si-e-allontanato-per-la-prima-volta-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/ora-ha-un-mondo-suo-oltre-la-sua-famiglia-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/in-vacanza-tutto-come-se-si-trattasse-di-un-gioco-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/adesso-fa-la-quarta-sta-ancora-con-noi-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/fu-in-tenda-che-mi-diede-il-benvenuto-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/come-mettere-in-quattro-righe-oltre-10-anni-di-vita-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/ci-hanno-scritto-n-21-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/apriamo-il-sipario-oggi-si-recita-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/il-ruolo-del-pediatra-nel-trattamento-del-bambino-handicappato-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/notiziario-fede-e-luce-n-21-2/": "/it/letture-consigliate-il-piccolo-principe/",
  "/beati-i-poveri-suggerimenti-per-le-tra-giornate-ad-assisi-1978-2/": "/it/il-cantico-delle-creature/",
  "/ciao-gianluca-2/": "/it/il-cantico-delle-creature/",
  "/tre-giorni-ad-assisi-2/": "/it/il-cantico-delle-creature/",
  "/qualche-informazione-prima-di-partire-per-il-pellegrinaggio-di-assisi-2/": "/it/il-cantico-delle-creature/",
  "/pappagalli-verdi-cronache-di-un-chirurgo-di-guerra/": "/it/pappagalli-verdi-cronache-di-un-chirurgo-di-guerra-recensione/",
  "/viola-e-mimosa-n-140-2/": "/it/caro-raffa-la-vita-e-adesso/",
  "/anna-che-sorride-alla-pioggia-recensione-2/": "/it/caro-raffa-la-vita-e-adesso/",
  "/niccolo-tra-coloro-che-hanno-fatto-la-storia/": "/it/ol-incontra-jorit/",
  "/come-doro/": "/it/come-loro/",
  "/biografilm/": "/it/biografilm-festival-2020/",
  "/squizo/": "/it/sqizo/",
  "/qualcosa-e-cambiato-2/": "/it/i-geni-del-futuro-crispr-cas9/",
  "/visto-al-cineforum-di-fede-e-luce-2/": "/it/i-geni-del-futuro-crispr-cas9/",
  "/ho-amici-in-paradiso-recensione-2/": "/it/i-geni-del-futuro-crispr-cas9/",
  "/dialogo-aperto-n-137-2/": "/it/i-geni-del-futuro-crispr-cas9/",
  "/dalle-province-n-137-2/": "/it/i-geni-del-passato-handiche/",
  "/una-veglia-laboratorio-per-il-giovedi-santo-2/": "/it/i-geni-del-passato-handiche/",
  "/viola-e-mimosa-n-137-2/": "/it/labilita-onlus-aprire-gli-occhi/",
  "/seveso-1976-oltre-la-diossina-2/": "/it/labilita-onlus-aprire-gli-occhi/",
  "/leutanasia-di-dio-recensione-2/": "/it/attesi-amati-trasformati/",
  "/i-geni-del-futuro-crispr-cas9-2/": "/it/abitare-nellordinarieta/",
  "/viaggio-a-parma-del-1976-unesperienza-di-gioia-condivisione-e-scoperta-con-fede-e-luce-2/": "/it/notiziario-di-fede-e-luce-n-10-1976/",
  "/un-angolino-di-arche-2/": "/it/notiziario-di-fede-e-luce-n-10-1976/",
  "/storia-dellaborto-i-molti-protagonisti-e-interessi-di-una-lunga-vicenda/": "/it/storia-dellaborto-i-molti-protagonisti-e-interessi-di-una-lunga-vicenda-recensione/",
  "/per-voi-e-per-tutti-consigli-pratici-perche-ne/": "/it/per-voi-e-per-tutti-consigli-pratici-perche-nessuno-venga-rifiutato/",
  "/il-male-ela-sofferenza-raccontati-ai-bambini/": "/it/il-male-e-la-sofferenza-raccontati-ai-bambini-recensione/",
  "/tu-sei-amato-da-dio-cosi-come-sei-2/": "/it/anffas-ogni-persona-con-disabiltia-e-nostro-figlio/",
  "/viola-e-mimosa-a-manila-2/": "/it/anffas-ogni-persona-con-disabiltia-e-nostro-figlio/",
  "/alfedena-per-immagini/": "/it/alfedena/",
  "/lettera-a-jean-matteo-mazzarotto/": "/it/lettere-a-jean-matteo-mazzarotto/",
  "/coltivare-i-propri-pensieri/": "/it/dialogo-aperto-n-112/",
  "/per-una-vera-qualita-di-cura/": "/it/dialogo-aperto-n-112/",
  "/il-mio-curriculum/": "/it/benedetta-il-mio-curriculum/",
  "/liberi-di-vivere-come-tutti/": "/it/liberi-di-vivere-come-tutti-prima-conferenza-nazionale-delle-politiche-sull-handicap/",
  "/i-nostri-grandi-amici-maria-teresa/": "/it/maria-teresa-di-calcutta-dedicato-ai-bambini/",
  "/viola-e-mimosa-n-138/": "/it/guidati-da-gio/",
  "/dedicato-ai-bambini-francesco/": "/it/dedicato-ai-bambini-francesco-gammarelli/",
  "/io-sono-una-donna/": "/it/io-sono-una-donna-perche-mi-chiami-andicappata/",
  "/io-sono-una-donna-perche-mi-chiamai-andicappata/": "/it/io-sono-una-donna-perche-mi-chiami-andicappata/",
  "/il-progetto-girotondo-2/": "/it/cervelli-ribelli-connettiamoci-neurodiversita/",
  "/da-fratello-e-da-padre-2/": "/it/cervelli-ribelli-connettiamoci-neurodiversita/",
  "/cervelli-ribelli/": "/it/cervelli-ribelli-connettiamoci-neurodiversita/",
  "/pellegrinaggio-assisi-1978-secondo-luis-sankale/": "/it/vita-fede-e-luce-natale-1977-a/",
  "/leducazione-delle-persone-disabili-imparare-a-mangiare-insieme-e-in-autonomia-2/": "/it/vita-fede-e-luce-natale-1977-a/",
  "/la-comunita-di-capodarco-2/": "/it/vita-fede-e-luce-natale-1977-a/",
  "/tempo-di-imparare/": "/it/tempo-di-imparare-valeria-parrella-recensione-libro/",
  "/blog-di-benedetta/": "/it/tanto-io-non-la-perdo/",
  "/il-dilemma-della-valutazione-2/": "/it/la-mia-disavventura/",
  "/costretta-a-legarmi-i-capelli-e-la-regola/": "/it/ho-imparato-da-sola-a-divertirmi/",
  "/messaggio-del-santo-padre-in-occasione-della-giornata-mondiale-delle-persone-con-disabilita/": "/it/papa-francesco-disabilita-messaggio/",
  "/base-per-articolo-benedetta-19-dicembre-2019/": "/it/non-mi-piace-cucinare/",
  "/unica-del-suo-genere/": "/it/unica-nel-suo-genere/",
  "/i-ciechi-non-sognano-il-buio-vivere-con-successo-la-cecita/": "/it/i-ciechi-non-sognano-il-buio-vivere-con-successo-la-cecita-recensione/",
  "/la-mia-disavventura-2/": "/it/la-mia-vita-a-santa-palomba/",
  "/i-saggi-sulloperazione-t4/": "/it/zavorre-prescelti/",
  "/dopo-di-me-il-diluvio/": "/it/dopo-di-me-il-diluvio-commedia-musicale-gruppo-fede-luce-san-paolo/",
  "/un-libro-interessante-chi-sarei-se-potessi-essere/": "/it/un-libro-interessante-adolescenza-ragazzi-disabili-chi-sarei-se-potessi-esserebozza-automatica/",
  "/un-libro-interessante-chi-sarei-se-potessi-esserebozza-automatica/": "/it/un-libro-interessante-adolescenza-ragazzi-disabili-chi-sarei-se-potessi-esserebozza-automatica/",
  "/se-la-teologia-non-sa-parlare-di-dio-comprendendo-la-disabilita-e-la-teologia-a-essere-disabile/": "/it/teologia-disabile/",
  "/newsletter-n-10/": "/it/newsletter-n-10-sulla-regia-non-credente-di-lourdes/",
  "/papa-san-pietro/": "/it/sulla-barca-in-piazza-san-pietro/",
  "/da-vicino-nessuno-e-disabile/": "/it/festival-diritti-umani/",
  "/la-sfida-di-rileggere-le-scene-del-cinema/": "/it/sensuability/",
  "/se-le-immagini-parlano-piu-delle-parole-newsletter-n-15/": "/it/newsletter-15/",
  "/cervelli-ribelli-connettiamoci-alla-neurodiversita/": "/it/dalle-province-n-141/",
  "/perche-tutti-comprendano-2/": "/it/dalle-province-n-141/",
  "/tracciare-il-sentiero-in-albania-2/": "/it/dalle-province-n-141/",
  "/spazio-aperto-una-coopera/": "/it/spazio-aperto-una-cooperativa-di-servizi/",
  "/monaci-di-lanuvio/": "/it/monaci-di-lanuvio-finanziamento-banca-etica/",
  "/parliamo-di-comunicazione-facilitata/": "/it/parliamo-di-comunicazione-facilitata-intervista-francesca-benassi/",
  "/la-lezione-di-un-clown/": "/it/la-lezione-di-un-clown-miloud-oukili/",
  "/tra-lame-che-affondano-e-ferite-medicate/": "/it/eredita-dei-vivi-recensione/",
  "/insieme/": "/it/insieme-primo-articolo/",
  "/lettera-di-daucourt-alle-comunita-dellarca/": "/it/nonostante-jean-vanier-larca-rimane/",
  "/i-panzerotti-di-caterina/": "/it/lo-scatto-della-pantera/",
  "/gli-amici-dei-bimbi/": "/it/gli-amici-dei-bimbi-reparto-gesu-bambino-istituto-santeusebio-vercelli/",
  "/la-luce-simbolo-del-pellegrinaggio-di-roma-1975-2/": "/it/per-te-ho-visitato-roma/",
  "/perche-proprio-a-roma-il-pellegrinaggio-del-1975-2/": "/it/per-te-ho-visitato-roma/",
  "/la-bimba-delle-lumache/": "/it/la-bimba-delle-lumache-recensione-libro/",
  "/nessuno-bambino-nasce-cattivo/": "/it/nessuno-bambino-nasce-cattivo-recensione-libro/",
  "/noi-quattro/": "/it/noi-quattro-la-comunita-il-roveto/",
  "/il-roveto/": "/it/comunita-il-roveto/",
  "/dallassistenza-allesistenza-sei-workshop-dellassociazione-vedere-oltre-onlus-2/": "/it/valgo-anchio/",
  "/fede-e-luce-una-scuola-di-altruismo-2/": "/it/valgo-anchio/",
  "/a-43/": "/it/a-4300-metri-di-altitudine-newsletter-n-31/",
  "/dove-crescono-i-cocomeri-di-cindy-baldwin-recensione/": "/it/dove-crescono-i-cocomeri-recensione/",
  "/marie-la-strabica-di-georges-simenon-recensione/": "/it/marie-la-strabica-recensione/",
  "/viaggio-italia-around-the-world/": "/it/viaggio-italia-recensione/",
  "/grazi/": "/it/grazie-papa-don-carlo-recensione/",
  "/dobbiamo-esser-prudenti-non-congelati/": "/it/ol-incontra-luigi-derrico/",
  "/una-mattina-ti-ho-osservato-mentre-ti-svegliavi/": "/it/ricordo-daniele-corrias/",
  "/la-piccola-artista-di-chartres/": "/it/recensione-i-disegni-segreti/",
  "/dopo-di-noi-i-diritti-che-ci-sono-2/": "/it/mamma-in-comunita/",
  "/lonore-di-un-lord-2/": "/it/mamma-in-comunita/",
  "/la-nuova-legge-sul-dopo-di-noi-nodi-da-sciogliere-2/": "/it/insolito-ragionamento-sul-migrante/",
  "/onora-il-padree-e-la-madre-pagine-di-tutti-i-tempi-per-capire-il-rapporto-tra-genitori-e-figli-recensione-libro/": "/it/onora-il-padre-e-la-madre-pagine-di-tutti-i-tempi-per-capire-il-rapporto-tra-genitori-e-figli-recensione-libro/",
  "/la-necessita-di-un-contesto-per-capire/": "/it/la-bellezza-nella-mente-recensione/",
  "/le-comunita-di-fede-e-luce-nellest-europeo/": "/it/comunita-fede-e-luce-nel-mondo-tante-piccole-fiaccole-di-unita-e-di-amore/",
  "/lecumenismo-in-fede-e-luce/": "/it/lecumenismo-in-fede-e-luce-un-dono/",
  "/perche-porto-i-miei-figli-a-fede-e-luce/": "/it/quando-porto-i-miei-figli-a-fede-e-luce-resto-incantata/",
  "/mi-trovo-bene-con-tuttmi-trovo-bene-con-tuttii/": "/it/mi-trovo-bene-con-tutti/",
  "/sessualita-e-disabilita-il-meglio-e-il-peggio-parlano-gli-educatori/": "/it/sessualita-e-disabilita-il-meglio-e-il-peggio/",
  "/amore-e-disabilita-facile-preda-dei-genitori/": "/it/amore-disabilita-facile-preda/",
  "/v-conferenza-internazionale-sullautismo-1983/": "/it/5-conferenza-internazionale-sullautismo-1983/",
  "/marahba-kiffak-ciao-come-stai/": "/it/marahba-kiffak-ciao-come-stai-fede-luce-beirut/",
  "/dallosservatorio-scolastico-deir-ai-as-di-milano/": "/it/scuola-e-disabilita-dallosservatorio-scolastico-deir-ai-as-di-milano/",
  "/ieri-oggi-domani-2/": "/it/dossier-scuola-e-disabilita/",
  "/dossier-scola-e-disabilita/": "/it/dossier-scuola-e-disabilita/",
  "/fede-e-luce-tutti-a-leeds-2/": "/it/dossier-scuola-e-disabilita/",
  "/che-fanfara-2/": "/it/dossier-scuola-e-disabilita/",
  "/7-idee-sulla-sindrome-di-down-2/": "/it/dossier-scuola-e-disabilita/",
  "/dalle-provice-n-141/": "/it/dialogo-aperto-n-141/",
  "/migrati-diverse-fragilita-si-incontrano-2/": "/it/i-figli-sono-tutti-speciali/",
  "/la-nuova-legge-sul-dopo-di-noi-che-cosa-dice-2/": "/it/i-figli-sono-tutti-speciali/",
  "/insolito-ragionamento-sul-migrante-2/": "/it/costruiamo-laccoglienza/",
  "/voglia-di-comunicare-2/": "/it/dialogo-aperto-n-142/",
  "/la-mia-forza-nella-mia-differenza-2/": "/it/percorsi-inclusivi-noi-ci-teniamo/",
  "/due-capitane-2/": "/it/percorsi-inclusivi-noi-ci-teniamo/",
  "/dal-convegno-allimpegno-2/": "/it/percorsi-inclusivi-noi-ci-teniamo/",
  "/dialogo-aperto-n-142-2/": "/it/la-comunicazione-multimodale/",
  "/gioco-test/": "/it/giochi-2022/",
  "/insieme-a-tutti-gli-altri-anche-mia-figlia-ha-ricevuto-la-cresima/": "/it/mia-figlia-adea-cresima/",
  "/lotta-per-linclusione/": "/it/lotta-per-linclusione-recensione/",
  "/la-nostra-scelta-di-cristina-2/": "/it/mai-piu-soli/",
  "/superata-lultima-sala-daspetto-2/": "/it/mai-piu-soli/",
  "/aggiungi-un-posto-a-casa-adozione-di-bambini-con-disabilita-2/": "/it/mai-piu-soli/",
  "/un-vescovo-per-amico-2/": "/it/mai-piu-soli/",
  "/dialogo-aperto-n-120-2/": "/it/mai-piu-soli/",
  "/cinema-la-disabilita-al-torino-film-festival-e-al-babel-film-festival-di-cagliari/": "/it/cinema-disabilita-torino-film-festival-babel-film-festival-di-cagliari/",
  "/sara-e-le-sbiruline-di-emily/": "/it/sara-e-le-sbiruline-di-emily-recensione/",
  "/il-vecchio-re-nel-suo-esilio-recensione-2/": "/it/franz-werfel-gallucci-editore-pp-722/",
  "/sara-e-le-sbiruline-di-emily-recensione-2/": "/it/odoardo-focherini-un-giusto-fra-le-nazioni-recensione/",
  "/rico-oscar-e-il-ladro-ombra-recensione-2/": "/it/la-caduta-i-ricordi-di-un-padre-in-424-passi-recensione/",
  "/io-mi-domando-2/": "/it/gli-altri-vostri-figli-lhanno-accettato/",
  "/ci-hanno-scritto-insieme-n-23-2/": "/it/gli-altri-vostri-figli-lhanno-accettato/",
  "/25-numero-6-anno-2/": "/it/gli-altri-vostri-figli-lhanno-accettato/",
  "/mio-figlio-emanuele-la-straordinaria-esperienza-di-una-madre-recensione-2/": "/it/un-figlio-handicappato/",
  "/notiziario-fede-e-luce-n-12-marzo-1977-2/": "/it/un-figlio-handicappato/",
  "/come-nata-la-prima-casetta-fede-e-luce-storie-di-pennelli-e-appendiciti-2/": "/it/un-figlio-handicappato/",
  "/visitiamo-con-maria-laura-il-centro-belga-per-infermi-motori-mentali-c-b-i-m-c/": "/it/un-figlio-handicappato/",
  "/inlusione-solidarieta-ordinaria/": "/it/inclusione-solidarieta-ordinaria/",
  "/abbiamo-un-cuore-inclusivo-2/": "/it/inclusione-solidarieta-ordinaria/",
  "/i-geni-del-passato-handiche-2/": "/it/inclusione-solidarieta-ordinaria/",
  "/per-il-rispetto-della-persona-sempre-2/": "/it/tra-incontri-nel-riconoscimento-dellaltro-puoi-ritrovare-fiducia/",
  "/la-cura-dellamore/": "/it/la-cura-dellamore-recensione/",
  "/legoismo-e-finito-recensione-2/": "/it/chiudi-gli-occhi-e-guardami-vivere-la-disabilita-in-famiglia-recensione/",
  "/voci-di-campo-2/": "/it/con-loro-ci-sto-bene/",
  "/bozza/": "/it/cani-pony-leoni-marini/",
  "/giubileo-2016-per-cominciare-una-nuova-storia-di-amore-2/": "/it/tutti-a-bordo/",
  "/il-vangelo-mimato-per-costruire-ponti-2/": "/it/tutti-a-bordo/",
  "/invitati-alla-festa/": "/it/associazione-invitati-alla-festa/",
  "/un-dado-vegetale-da-sogno-e-fatto-in-casa-2/": "/it/essere-padre-di-un-figlio-disabile/",
  "/il-libro-di-julian-a-wonder-story-recensione-2/": "/it/un-ponte-in-un-guscio-di-noce/",
  "/zia-lo-sai-che-sei-un-po-strana-recensione-2/": "/it/un-ponte-in-un-guscio-di-noce/",
  "/il-bambino-che-parlava-con-la-luce-recensione-2/": "/it/un-ponte-in-un-guscio-di-noce/",
  "/riuniti-in-preghiera-2/": "/it/un-ponte-in-un-guscio-di-noce/",
  "/il-canto-di-bernadette-recensione/": "/it/pensioni-rubate/",
  "/famiglie-in-esilio-ferite-ritrovate-riconciliate-recensione-2/": "/it/pensioni-rubate/",
  "/due-grandi-occhi-neri-2/": "/it/julia-jean-e-la-tirannia-della-normalita/",
  "/la-mia-vita-a-santa-palomba-2/": "/it/si-ricomincia/",
  "/katimavik-una-parola-escquimese-che-vuol-dire-incontro/": "/it/katimavik-una-parola-eschimese-che-vuol-dire-incontro/",
  "/ziguli/": "/it/ziguli-recensione/",
  "/ci-hanno-scritto-insieme-n-27-2/": "/it/marina-di-camerota-venti-giorni-di-prime-volte/",
  "/fratelli-e-sorelle-di-persone-con-disabilita-una-realta-da-riscoprire-2/": "/it/marina-di-camerota-venti-giorni-di-prime-volte/",
  "/lavventura-di-oletta-quando-il-cavallo-diventa-terapia-2/": "/it/marina-di-camerota-venti-giorni-di-prime-volte/",
  "/dossier-vite-da-ri-accogliere-adolescenti-allo-sbaraglio/": "/it/adolescenti-allo-sbaraglio/",
  "/alto-come-un-vaso-di-gerani-recensione-2/": "/it/respiro-dopo-respiro-lo-yoga-per-bambini-e-adolescenti-con-bisogni-speciali/",
  "/parole-in-liberta-diario-semiserio-della-madre-di-un-disabile-recensione-2/": "/it/respiro-dopo-respiro-lo-yoga-per-bambini-e-adolescenti-con-bisogni-speciali/",
  "/un-castello-di-sabbia-storia-della-mia-vita-e-della-mia-schizofrenia-recensione-2/": "/it/respiro-dopo-respiro-lo-yoga-per-bambini-e-adolescenti-con-bisogni-speciali/",
  "/dallo-stadio-al-palazzetto/": "/it/anche-io-tiro-i-rigori/",
  "/dialogo-aperto-n-125-2/": "/it/viola-e-valeria/",
  "/un-gioco-da-fare-quando-fuori-piove-2/": "/it/viola-e-valeria/",
  "/hotel-6-stelle-2/": "/it/viola-e-valeria/",
  "/germogli-diversi-arte-floreale-e-disabilita-la-bellezza-di-un-percorso-possibile-2/": "/it/viola-e-valeria/",
  "/chopin-diversamente-impresa-2/": "/it/viola-e-valeria/",
  "/artiste-nellorto-2/": "/it/viola-e-valeria/",
  "/julia-jean-e-la-tirannia-della-normalita-2/": "/it/lettere-a-jean-don-marco-bove-2/",
  "/auguri-scomodi-per-il-nuovo-anno-2/": "/it/lettere-a-jean-don-marco-bove-2/",
  "/sotto-lo-stesso-tetto-casa-famiglia-il-tetto/": "/it/casa-famiglia-il-tetto/",
  "/pulce-non-ce-recensione-2/": "/it/quali-mani-asciugheranno-le-mie-lacrime-recensione/",
  "/elogio-della-fragilita/": "/it/elogio-della-fragilita-recensione/",
  "/chiudi-gli-occhi-e-guardami-vivere-la-disabilita-in-famiglia-recensione-2/": "/it/dalle-province-n-122/",
  "/casa-famiglia-iniziativa-amica-bambini-che-vanno-bambini-che-vengono/": "/it/iniziativa-amica-una-casa-famiglia-dove-la-maternita-ritorna-gioia/",
  "/connessi-per-davvero-2/": "/it/dialogo-aperto-n-139/",
  "/hello-harry-hi-benny-recensione-2/": "/it/dialogo-aperto-n-139/",
  "/il-signor-parroco-ha-dato-di-matto-2/": "/it/dialogo-aperto-n-139/",
  "/dopo-di-noi-atti-del-convegno-anffas-2/": "/it/dialogo-aperto-n-139/",
  "/un-crocifisso-silenzioso-immagine-della-rivoluzione-cristiana/": "/it/essere-mamma/",
  "/dialogo-aperto-n-84/": "/it/dialogo-aperto-n-85/",
  "/oscura-luminosissima-notte/": "/it/oscura-luminosissima-notte-recensione/",
  "/bisogna-accettare-che-un-bambino-abbia-delle-resistenze-2/": "/it/io-e-simona/",
  "/quattro-giorni-mano-nella-mano-2/": "/it/io-e-simona/",
  "/don-gnocchi-una-vita-spesa-per-gli-altri-recensione-2/": "/it/dalle-province-n-138/",
  "/gli-scartagonisti-recensione-2/": "/it/dalle-province-n-138/",
  "/lamniocentesi-di-stato-e-la-grande-colpa-di-madri-selvagge-recensione/": "/it/lamniocentesi-di-stato-e-la-grande-colpa-di-noi-madri-selvagge-recensione/",
  "/ce-labbiamo-fatta-2/": "/it/ciclisti-non-vedenti-vaticano/",
  "/da-bologna-a-roma-in-tandem-un-ciclo-viaggio-oltre-la-disabilita/": "/it/da-bologna-a-roma-in-tandem/",
  "/da-bologna-a-roma-in-tandem-un-ciclo-viaggio/": "/it/da-bologna-a-roma-in-tandem/",
  "/safesurfing-navigare-nella-rete-in-sicurezza-2/": "/it/il-plusabile-due-sorelle-speciali/",
  "/dalle-province-n-139-2/": "/it/il-plusabile-due-sorelle-speciali/",
  "/viola-e-mimosa-n-139-2/": "/it/il-plusabile-due-sorelle-speciali/",
  "/segni-efficaci-2/": "/it/il-plusabile-due-sorelle-speciali/",
  "/la-sua-prima-confessione-2/": "/it/il-plusabile-due-sorelle-speciali/",
  "/benedetta-mi-convertito/": "/it/benedetta-mi-ha-convertito/",
  "/noi-dei-piani-di-sopra/": "/it/storia-redazione-via-bessarione-gammarelli/",
  "/coltivare-propri-pensieri/": "/it/coltivare-propri-desideri/",
  "/per-una-vera-qualita-di-cura-delle-persone-anziane-2/": "/it/coltivare-propri-desideri/",
  "/il-coraggio-della-piccola-vanessa-2/": "/it/lui-la-guida-degli-uomini-e-rimasto-indietro-per-me/",
  "/perche-esista-e-dio-il-responsabile-del-mio-handicap/": "/it/perche-esiste-la-disabilita-e-dio-il-responsabile-del-mio-handicap/",
  "/ci-hanno-scritto-n-15-2/": "/it/come-bere-un-bicchier-dacqua/",
  "/pensioni-rubate-2/": "/it/quasi-amici-recensione/",
  "/berlinale-74-leone-doro/": "/it/berlinale-74-orso-doro/",
  "/lintimita-del-corpo-vita-tra-fratelli/": "/it/vita-tra-fratelli/",
  "/riscoprire-la-grazia-della-confessione-2/": "/it/dicono-di-loro/",
  "/lo-sapevate-che/": "/it/lo-sapevate-che-2/",
  "/dossier-scola-e-disabilita-2/": "/it/dialogo-aperto-n-123/",
  "/otto-giorni-per-ventanni/": "/it/arche-bologna-tandem/",
  "/dossier-vite-da-ri-accogliere-la-citta-dei-ragazzi-cittadini-del-mondo/": "/it/la-citta-dei-ragazzi/",
  "/dossier-vite-da-ri-accogliere-la-citta-dei-ragazzi/": "/it/la-citta-dei-ragazzi/",
  "/vite-da-ri-accogliere-la-citta-dei-ragazzi/": "/it/la-citta-dei-ragazzi/",
  "/essere-padre-di-un-figlio-disabile-2/": "/it/custodi-della-speranza/",
  "/obiettivo-decrescita-recensione/": "/it/ii-barattolo-di-maionese-e-caffe/",
  "/il-mo-cane-mi-ha-scelto/": "/it/il-mio-cane-mi-ha-scelto/",
  "/caro-raffa-la-vita-e-adesso-2/": "/it/fare-nuove-tutte-le-cose/",
  "/una-redazione-in-condominio/": "/it/noi-dei-piani-di-sopra/",
  "/le-chiavi-di-casa-recensione/": "/it/le-chiavi-di-casa-film/",
  "/dal-sostegno-alla-partecipazione-esperienze-di-educazione-inclusiva-per-bambini-con-difficolta-2/": "/it/scuola-viva-un-modello-di-inclusione-attiva-per-bambini-con-disabilita/",
  "/la-dove-tu-ci-vuoi-ogni-giorno-2/": "/it/scuola-viva-un-modello-di-inclusione-attiva-per-bambini-con-disabilita/",
  "/ci-hanno-scritto-insieme-n-28-2/": "/it/scuola-viva-un-modello-di-inclusione-attiva-per-bambini-con-disabilita/",
  "/il-loro-credo-2/": "/it/scuola-viva-un-modello-di-inclusione-attiva-per-bambini-con-disabilita/",
  "/i-nostri-figli-con-disabilita-a-scuola-2/": "/it/scuola-viva-un-modello-di-inclusione-attiva-per-bambini-con-disabilita/",
  "/sotto-cieli-noncuranti-recensione-2/": "/it/sembrava-impossibile-dove-osano-le-aquile-in-carrozzina-recensione/",
  "/la-scelta-di-ivana/": "/it/la-scelta-di-ivana-la-mia-vita-al-carro/",
  "/ulamministratore-di-sostegno-per-le-persone-con-disabilita/": "/it/una-nuova-legge-lamministratore-di-sostegno-per-le-persone-con-disabilita/",
  "/presentazione-festival/": "/it/san-sebastian-il-piu-piccolo-dei-grandi-festival/",
  "/dialogo-aperto-n-138-2/": "/it/sara-bello/",
  "/pretese-fuori-mercato-2/": "/it/dialogo-aperto-n-161/",
  "/dalla-festa-del-cinema-di-roma/": "/it/festa-del-cinema-roma-2023/",
  "/la-casa-di-dario/": "/it/la-casa-di-dario-comunita-alloggio/",
  "/sara-bello-2/": "/it/dossier-rifugiati/",
  "/il-mondo-come-lo-vediamo-noi/": "/it/recensione-as-we-see-it/",
  "/fede-e-luce-larca-ombre-e-luci-tre-vocazioni-ununica-ispirazione/": "/it/fede-e-luce-larca-ombre-e-luci/",
  "/a-a-a-una-mamma-chiede-una-mamma-risponde/": "/it/sulleducazione-delle-giovani-generazioni-una-mamma-chiede-una-mamma-risponde/",
  "/fare-nuove-tutte-le-cose-2/": "/it/le-amiche-di-francesco/",
  "/io-non-voglio-estranei-in-casa-2/": "/it/per-rompere-la-solitudine-2/",
  "/presena-reale/": "/it/presenza-reale/",
  "/storia-di-un-segreto-dio-mi-ha-parlato-tramite-i-miei-amici-speciali-2/": "/it/1971-2011-fede-e-luce-festeggia-40-anni/",
  "/special-olimpics/": "/it/special-olympics-nessuno-si-deve-sentire-escluso/",
  "/special-olimpics-nessuno-si-deve-sentire-escluso/": "/it/special-olympics-nessuno-si-deve-sentire-escluso/",
  "/un-incontro-tra-capi/": "/it/un-incontro-tra-capi-scout/",
  "/portatrice-di-un-messaggio-2/": "/it/grazie-mariangela/",
  "/borderline-recensione-2/": "/it/grazie-mariangela/",
  "/viola-e-il-messico-2/": "/it/grazie-mariangela/",
  "/lettera-di-jean-n-126-2/": "/it/grazie-mariangela/",
  "/attivita-riabilitative-fiori-colori-e-profumi-2/": "/it/grazie-mariangela/",
  "/volevo-che-qualcuno-rispondesse-alle-mie-domande-2/": "/it/grazie-mariangela/",
  "/smack-come-bacio-il-mio-tempo-con-mio-figlio-disabile/": "/it/smack-come-bacio-il-tempo-con-mio-figlio-disabile/",
  "/noi-papa-di-fiun-modo-diverso-di-amare/": "/it/noi-papa-di-figli-disabili-un-modo-diverso-di-amare/",
  "/gli-oggetti-raccontano-storie-straordinarie-di-oggetti-comuni/": "/it/gli-oggetti-raccontano-storie-straordinarie-di-oggetti-comuni-recensione/",
  "/un-affidamento-speciale-2__trashed/": "/it/un-affidamento-speciale-2/",
  "/insegnante-di-lettere-canale-della-vita-2/": "/it/il-sorriso-dei-tuoi-occhi/",
  "/il-sorriso-dei-tuoi-occhi-2/": "/it/da-un-altro-punto-di-vista/",
  "/tra-incontri-nel-riconoscimento-dellaltro-puoi-ritrovare-fiducia-2/": "/it/la-nostra-presenza-accanto-a-lei/",
  "/con-la-forza-di-una-quercia/": "/it/agli-amici-vici-siate-disponibili/",
  "/fratelli-e-sorelle-di-persone-con-disabilita-2/": "/it/nella-diagnosi-siamo-prudenti/",
  "/la-cura-invisibile-per-il-riconoscimento-dei-caregiver-2/": "/it/nella-diagnosi-siamo-prudenti/",
  "/alla-ricerca-dellaltro-da-me/": "/it/testimonianza-giulia-cirillo/",
  "/se-avessi-ascoltato-la-mia-disperazione/": "/it/dialogo-aperto-n-95/",
  "/dalle-province-n-138-2/": "/it/trasformare-i-nostri-cuori/",
  "/ricordi-di-mia-madre-recensione-2/": "/it/perdersi-recensione/",
  "/dialogo-aperto-n-143-2/": "/it/dalle-province-n-143/",
  "/obiettivo-decrescita-ecensione/": "/it/obiettivo-decrescita-recensione/",
  "/mamma-in-comunita-2/": "/it/la-strada-percorsa-finora/",
  "/la-speranza-non-fa-rumore-recensione-3/": "/it/bioetica-come-storia-recensione/",
  "/un-figlio-handicappato-2/": "/it/editoriale-lettera-aperta-agli-amici-di-fede-e-luce/",
  "/cose-un-sacramento-cose-leucaristia-cose-la-confessione-2/": "/it/editoriale-lettera-aperta-agli-amici-di-fede-e-luce/",
  "/ci-hanno-scritto-n-12-2/": "/it/editoriale-lettera-aperta-agli-amici-di-fede-e-luce/",
  "/venerdi-poverta-assisi-1978/": "/it/quel-giorno-pioveva/",
  "/se-assisi-1978-2/": "/it/quel-giorno-pioveva/",
  "/corsa-in-taxi-2/": "/it/un-augurio-speciale/",
  "/gli-altri-vostri-figli-lhanno-accettato-2/": "/it/vita-fede-e-luce/",
  "/una-realta-esigente-2/": "/it/vita-fede-e-luce/",
  "/perche-non-mi-capisci-3/": "/it/vita-fede-e-luce/",
  "/mia-sorella-2/": "/it/vita-fede-e-luce/",
  "/non-e-facile-esprimere-2/": "/it/vita-fede-e-luce/",
  "/una-lettera-2/": "/it/vita-fede-e-luce/",
  "/la-mia-vita-2/": "/it/vita-fede-e-luce/",
  "/ciao-alessandro/": "/it/vita-fede-e-luce/",
  "/dialogo-aperto-n-135-2/": "/it/dalle-province-n-135/",
  "/mi-hanno-regalato-un-sogno-2/": "/it/dalle-province-n-135/",
  "/mio-figlio-un-angelo-che-ha-scelto-di-vivere/": "/it/mio-figlio-un-angelo-che-ha-scelto-di-vivere-recensione/",
  "/efrem-1/": "/it/impegnarsi-e-impegnarmi/",
  "/disabilmentemamma/": "/it/disabilmentemamme/",
  "/amore-caro-a-filo-doppio-con-persone-fragili/": "/it/amore-caro-a-filo-doppio-con-persone-fragili-recensione/",
  "/gli-esordi-insieme-1974-1981-2/": "/it/quattro-punti-cardinali-i-luoghi-di-ombre-e-luci-tra-i-quartieri-di-roma/",
  "/giubileo-2016-la-vera-gioia-2/": "/it/la-sfida-di-chi-ama-di-piu/",
  "/dialogo-aperto-n-139-2/": "/it/scoprirsi-unici-e-crescere-insieme/",
  "/come-and-see-meeting-dei-giovani-ad-alicante-2/": "/it/scoprirsi-unici-e-crescere-insieme/",
  "/la-chiesa-accanto-a-mio-figlio-2/": "/it/scoprirsi-unici-e-crescere-insieme/",
  "/ci-ha-lasciato-marie-odile-rhethore/": "/it/ci-ha-lasciato-la-professoressa-marie-odile-rhethore/",
  "/il-respiro-leggero-dellalba-recensione-2/": "/it/il-motivo-per-cui-salto-recensione/",
  "/tema-dellanno-1980-lincontro-2/": "/it/letture-consigliate-n-23/",
  "/al-rientro-dalle-vacanze-campeggi-campeggi-ancora-campeggi-2/": "/it/letture-consigliate-n-23/",
  "/marymount-unestate-di-musica-e-sorrisi-2/": "/it/letture-consigliate-n-23/",
  "/lordinazione-di-robert-michit-2/": "/it/letture-consigliate-n-23/",
  "/insieme-verso-la-pasqua-1981-2/": "/it/letture-consigliate-n-23/",
  "/qualche-raggio-di-sole-in-siria-2/": "/cercare-la-bellezza-la-dove-e-nascosta/",
  "/un-ponte-in-un-guscio-di-noce-2/": "/it/il-roveto-di-santilario/",
  "/spiritualmente-le-piccole-suore-non-sono-handicappate-2/": "/it/il-roveto-di-santilario/",
  "/antonietta-campo-estivo/": "/it/vivere-a-colori/",
  "/anffas-ogni-persona-con-disabilita-e-nostro-figlio/": "/it/istituto-mio-dio/",
  "/istituto-mio-dio-2/": "/it/il-tuo-bambino-ha-qualcosa-che-non-va/",
  "/nella-diagnosi-siamo-prudenti-2/": "/it/tra-paura-e-desiderio-di-sapere/",
  "/il-tuo-bambino-ha-qualcosa-che-non-va-2/": "/it/che-grinta/",
  "/tra-paura-e-desiderio-di-sapere-2/": "/it/dialogo-aperto-n-122/",
  "/non-possiamo-restare-dei-peter-pan-a-vita-2/": "/it/il-senso-di-una-vita-e-di-una-scelta/",
  "/cercare-la-bellezza-la-dove-e-nascosta-2/": "/it/il-senso-di-una-vita-e-di-una-scelta/",
  "/che-grinta-2/": "/it/ora-basta/",
  "/notiziario-fede-e-luce-dicembre-1976-2/": "/it/testimonianze-dai-campi-di-alfedena-1976/",
  "/la-comunicazione-multimodale-2/": "/it/segni-dellamore-di-dio/",
  "/segni-dellamore-di-dio-2/": "/it/ascoltare-i-segni-perche-in-lis/",
  "/fede-e-luce-anatomia-di-una-comunita-di-incontro/": "/it/1-introduzione-fede-e-luce-anatomia-di-una-comunita-di-incontro/",
  "/ci-hanno-scritto-insieme-n-24-2/": "/it/1-introduzione-fede-e-luce-anatomia-di-una-comunita-di-incontro/",
  "/ascoltare-i-segni-perche-in-lis-2/": "/it/fede-e-luce-una-grande-famiglia/",
  "/porta-sfortuna-2/": "/it/dialogo-aperto-n-133/",
  "/il-roveto-di-santilario-2/": "/it/dialogo-aperto-n-133/",
  "/la-disabilita-un-confine-da-superare-2/": "/it/chiamati-tutti-al-traguardo/",
  "/il-senso-di-una-vita-e-di-una-scelta-2/": "/it/chiamati-tutti-al-traguardo/",
  "/dalle-provincia-n-130-2/": "/it/il-senso-della-festa/",
  "/la-paura-di-amare-recensione-2/": "/it/il-senso-della-festa/",
  "/dialogo-aperto-n-130-2/": "/it/il-senso-della-festa/",
  "/il-senso-della-festa-2/": "/it/scintille-di-amicizia/",
  "/scintille-di-amicizia-2/": "/it/i-mille-volti/",
  "/i-mille-volti-2/": "/it/piu-scavo-piu-trovo/",
  "/il-motivo-per-cui-salto-recensione-2/": "/it/dialogo-aperto-n-126/",
  "/dialogo-aperto-n-126-2/": "/it/fede-e-luce-si-ci-siamo-anche-noi/",
  "/fede-e-luce-si-ci-siamo-anche-noi-2/": "/it/un-capo-atipico-per-larca/",
  "/un-capo-atipico-per-larca-2/": "/it/cristiani-del-sagrato/",
  "/cristiani-del-sagrato-2/": "/it/la-mia-lampada-frontale/",
  "/la-mia-lampada-frontale-2/": "/it/argento-vivo/",
  "/argento-vivo-2/": "/it/sulla-sua-strada/",
  "/da-un-altro-punto-di-vista-2/": "/it/con-orgoglio-e-tenerezza/",
  "/lamicizia-un-dono-unico-ed-eterno-2/": "/it/con-orgoglio-e-tenerezza/",
  "/labilita-onlus-aprire-gli-occhi-2/": "/it/avere-un-posto-nella-societa/",
  "/il-calore-dellamicizia-2/": "/it/una-ragazza-speciale/",
  "/vuoi-bene-a-gesu-2/": "/it/una-ragazza-speciale/",
  "/una-ragazza-speciale-2/": "/it/perche-ho-avuto-fiducia/",
  "/puo-un-gesto-essere-cosi-significativo-2/": "/it/un-oro-al-giorno/",
  "/chi-scalda-il-cuore-2/": "/it/un-oro-al-giorno/",
  "/cosa-ti-aspetti-2/": "/it/un-oro-al-giorno/",
  "/monsignor-von-galen-leroismo-di-una-coscienza-2/": "/it/un-oro-al-giorno/",
  "/il-giubileo-di-fede-e-luce-2/": "/it/un-oro-al-giorno/",
  "/dalle-province-n-135-2/": "/it/un-oro-al-giorno/",
  "/chiamati-a-portare-frutto-2/": "/it/un-oro-al-giorno/",
  "/la-lingua-dei-segni-nelle-disabilita-comunicative/": "/it/la-lingua-dei-segni-nelle-disabilita-comunicative-recensione/",
  "/marina-di-camerota-venti-giorni-di-prime-volte-2/": "/it/quante-domande-davanti-a-loro/",
  "/estate-fede-e-luce-1980-la-gioia-di-fare-vacanza-insieme-2/": "/it/quante-domande-davanti-a-loro/",
  "/campeggio-fede-e-luce-unavventura-di-vita-e-comunita-2/": "/it/quante-domande-davanti-a-loro/",
  "/un-aiuto-per-il-pellegrinaggio-di-lourdes-1981-chi-puo-darci-una-mano-2/": "/it/quante-domande-davanti-a-loro/",
  "/incontro-internazionale-e-nazionale-un-ponte-di-solidarieta-tra-paesi-e-comunita-2/": "/it/quante-domande-davanti-a-loro/",
  "/ogni-volta-che-lascio-alfedena-2/": "/it/quante-domande-davanti-a-loro/",
  "/darti-la-vita-2/": "/it/adulti-lievemente-handicappati/",
  "/vita-fede-e-luce-natale-1977-a-2/": "/it/assemblea-internazionale-di-fede-e-luce-a-bruxelles-gennaio-1978/",
  "/notiziario-fede-e-luce-n-16-2/": "/it/assemblea-internazionale-di-fede-e-luce-a-bruxelles-gennaio-1978/",
  "/esperienze-i-campi-dellestete-1977/": "/it/esperienze-i-campi-dellestate-1977/",
  "/scuola-e-disabilita-integrazione-ascoltiamo-le-testimonianze-di-due-mamme-2/": "/it/esperienze-i-campi-dellestate-1977/",
  "/come-bere-un-bicchier-dacqua-2/": "/it/esperienze-i-campi-dellestate-1977/",
  "/giovanissimi-2/": "/it/buon-natale-antico-corale-trascritto-da-un-bambino/",
  "/sono-tornato-stasera-2/": "/it/buon-natale-antico-corale-trascritto-da-un-bambino/",
  "/noris-2/": "/it/buon-natale-antico-corale-trascritto-da-un-bambino/",
  "/giovanissimi-n-3-2/": "/it/buon-natale-antico-corale-trascritto-da-un-bambino/",
  "/buon-natale-antico-corale-trascritto-da-un-bambino-2/": "/it/ci-ha-scritto-la-mamma-di-roberto/",
  "/per-la-nostra-riflessione-2/": "/it/letture-consigliate-n-18/",
  "/per-la-loro-educazione-visita-allistituto-statale-romagnolo-per-non-vedenti-2/": "/it/letture-consigliate-n-18/",
  "/esperienze-al-gruppo-fede-e-luce-la-mamma-di-massimo-2/": "/it/letture-consigliate-n-18/",
  "/come-un-raggio-di-sole-2/": "/it/letture-consigliate-n-18/",
  "/notiziario-fede-e-luce-n-18-2/": "/it/letture-consigliate-n-18/",
  "/vita-dei-gruppi-fede-e-luce-1978-2/": "/it/letture-consigliate-n-18/",
  "/festa-della-primavera-a-villa-pacis-1978-2/": "/it/letture-consigliate-n-18/",
  "/la-casetta-di-fede-e-luce-cose-che-fini-ha-chi-la-frequenta/": "/it/letture-consigliate-n-18/",
  "/fede-e-luce-anatomia-di-una-comunita-di-incontro-2/": "/it/5-creascere-insieme-guidare-una-comunita-fede-e-luce-principi-e-pratica/",
  "/fede-e-luce-larte-dellincontro-per-superare-la-paura-della-diversita-2/": "/it/5-creascere-insieme-guidare-una-comunita-fede-e-luce-principi-e-pratica/",
  "/costruire-comunita-i-tre-pilastri-di-fede-e-luce/": "/it/5-creascere-insieme-guidare-una-comunita-fede-e-luce-principi-e-pratica/",
  "/guidare-una-comunita-fede-e-luce-principi-e-pratica/": "/it/5-creascere-insieme-guidare-una-comunita-fede-e-luce-principi-e-pratica/",
  "/esperienze-i-campi-dellestate-1977-2/": "/it/notiziario-fede-e-luce-calendario-1978/",
  "/notiziario-fede-e-luce-1978/": "/it/notiziario-fede-e-luce-calendario-1978/",
  "/costruire-comunita-tre-pilastri-fede-luce/": "/it/4-vita-comunitaria-costruire-comunita-tre-pilastri-fede-luce/",
  "/i-volti-di-fede-e-luce-persona-con-disabilita-genitori-amici-e-sacerdoti-2/": "/it/4-vita-comunitaria-costruire-comunita-tre-pilastri-fede-luce/",
  "/ci-hanno-scritto-n-20-2/": "/it/notiziario-fede-e-luce-n-20/",
  "/7-testimonianze-di-genitori-e-amici-di-bambini-profondamente-handicappati-2/": "/it/notiziario-fede-e-luce-n-20/",
  "/la-forestiere-vita-comunitaria-con-i-piu-gravi-allarche-2/": "/it/notiziario-fede-e-luce-n-20/",
  "/ci-ha-scritto-la-mamma-di-roberto-2/": "/it/avevano-bisogno-di-noi/",
  "/di-serie-promettenti-e-film-non-riusciti-alla-festa-del-cinema-di-roma/": "/it/recensione-te-lavevo-detto-la-storia/",
  "/notiziario-fede-e-luce-calendario-del-prossimo-anno/": "/it/bando-di-concorso-per-auto-adesivo-del-pellegrinaggio/",
  "/un-giro-in-tandem/": "/it/il-mio-primo-giro-in-bici/",
  "/meditazione-a-modo-mio-2/": "/it/jean-vanier-a-parma-1978/",
  "/quel-giorno-pioveva-2/": "/it/jean-vanier-a-parma-1978/",
  "/5-crescere-insieme-guidare-una-comunita-fede-e-luce-principi-e-pratica/": "/it/andiamo-tutti-in-pizzeria/",
  "/lourdes-qui-e-oggi/": "/it/andiamo-tutti-in-pizzeria/",
  "/vita-fede-e-luce-n-24-2/": "/it/andiamo-tutti-in-pizzeria/",
  "/pellegrinaggio-a-loreto-18-20-maggio-1979-2/": "/it/gita-ad-argegno-3-giugno-1979/",
  "/pellegrinaggio-a-loreto-1979-le-testimonianze-dei-partecipanti/": "/it/gita-ad-argegno-3-giugno-1979/",
  "/23-maggio-1979-festa-della-primavera-2/": "/it/gita-ad-argegno-3-giugno-1979/",
  "/gita-ad-argegno-3-giugno-1979-2/": "/it/vita-fede-e-luce-n-22-1979/",
  "/vita-fede-e-luce-n-22-1979-2/": "/it/letture-consigliate-n-22/",
  "/cosa-vedremo-a-roma-durante-il-pellegrinaggio-1975-2/": "/it/i-canti-del-pellegrinaggio-di-roma-1975/",
  "/per-te-ho-visitato-roma-2/": "/it/i-canti-del-pellegrinaggio-di-roma-1975/",
  "/testimonianze-dal-pellegrinaggio-di-lourdes-1971-2/": "/it/i-canti-del-pellegrinaggio-di-roma-1975/",
  "/i-volti-di-fede-e-luce-persona-con-disabilita-genitori-amici-e-sacerdoti/": "/it/3-i-protagonisti-i-volti-di-fede-e-luce-persona-con-disabilita-genitori-amici-e-sacerdoti/",
  "/il-mio-quinto-concerto-di-baglioni/": "/it/benedetta-baglioni/",
  "/leco-della-stampa-2/": "/it/ricordi-e-speranze-dai-questionari-sul-pellegrinaggio-a-roma-del-1975/",
  "/ricordi-e-speranze-dai-questionari-sul-pellegrinaggio-a-roma-del-1975-2/": "/it/giovanissimi-n-7/",
  "/giovanissimi-n-7-2/": "/it/tavola-rotonda/",
  "/tavola-rotonda-2/": "/it/dietro-le-quinte/",
  "/dietro-le-quinte-2/": "/it/il-problema-dellacqua/",
  "/il-problema-dellacqua-2/": "/it/la-nostra-buona-novella/",
  "/avevano-bisogno-di-noi-2/": "/it/resoconti-degli-incontri-fede-e-luce/",
  "/scuola-viva-un-modello-di-inclusione-attiva-per-bambini-con-disabilita-2/": "/it/vita-fede-e-luce-insieme-n-28/",
  "/techniche-di-recupero-per-i-disabili-gravi-la-socializzazione/": "/it/tecniche-di-recupero-per-i-disabili-gravi-la-socializzazione/",
  "/fede-e-luce-larte-dellincontro-per-superare-la-paura-della-diversita/": "/it/2-fede-e-luce-larte-dellincontro-per-superare-la-paura-della-diversita/",
  "/3-vincitori-e-non/": "/it/san-sebastian-festival-tardes-de-soledad/",
  "/letture-consigliate-n-13/": "/it/letture-consigliate-n-14/",
  "/vita-fede-e-luce-insieme-n-28-2/": "/it/la-vendita-di-novembre-impegno-e-solidarieta/",
  "/together-a-san-pietro-2/": "/it/mimo-a-san-pietro/",
  "/quando-arrivia-il-natale/": "/it/quando-arriva-il-natale/",
  "/vita-fede-e-luce-insieme-n-25/": "/it/e-uscita-una-nuova-legge-sullassegno-di-accompagnamento-per-le-persone-totalmente-inabili/",
  "/e-uscita-una-nuova-legge-sullassegno-di-accompagnamento-per-le-persone-totalmente-inabili-2/": "/it/letture-consigliate-la-vita-puo-ricominciare-recensione/",
  "/partiamo-per-il-congo/": "/it/partiamo-per-il-congo-caa/",
  "/letture-consigliate-la-vita-puo-ricominciare-recensione-2/": "/it/questionario-per-i-fratelli-e-sorrelle-di-persone-con-disabilita/",
  "/notiziario-fede-e-luce-n-20-2/": "/it/che-cose-un-katimavic/",
  "/che-cose-un-katimavic-2/": "/it/letture-consigliate-lo-svantaggiato-quale-educazione/",
  "/la-vendita-di-novembre-impegno-e-solidarieta-2/": "/it/incontro-internazionale-preparativi-e-spiritualita/",
  "/via-plinio-30-2/": "/it/telegramma-educarsi-insieme-crescere-con-gli-altri-per-il-bene-di-tutti/",
  "/ci-hanno-scritto-insieme-n-26-2/": "/it/telegramma-educarsi-insieme-crescere-con-gli-altri-per-il-bene-di-tutti/",
  "/dalla-parte-di-lazzaro-2/": "/it/telegramma-educarsi-insieme-crescere-con-gli-altri-per-il-bene-di-tutti/",
  "/5-anni-di-casetta-2/": "/it/telegramma-educarsi-insieme-crescere-con-gli-altri-per-il-bene-di-tutti/",
  "/andiamo-alla-casetta-2/": "/it/telegramma-educarsi-insieme-crescere-con-gli-altri-per-il-bene-di-tutti/",
  "/telegramma-educarsi-insieme-crescere-con-gli-altri-per-il-bene-di-tutti-2/": "/it/un-problema-che-non-so-risolvere/",
  "/un-problema-che-non-so-risolvere-2/": "/it/vita-fede-e-luce-insieme-n-26/",
  "/vita-fede-e-luce-insieme-n-26-2/": "/it/letture-consigliate-n-26/",
  "/fede-e-luce-un-po-di-storia/": "/it/la-festa-continua/",
  "/amici-delicati-e-fedeli-2/": "/it/la-festa-continua/",
  "/gioia-di-essere-sacerdote-2/": "/it/la-festa-continua/",
  "/la-lettera-del-papa-wojtyla-2/": "/it/la-festa-continua/",
  "/avevo-paura-2/": "/it/la-festa-continua/",
  "/come-avviare-una-comunita-2/": "/it/la-festa-continua/",
  "/perche-un-numero-dedicato-allanimazione-2/": "/it/la-festa-continua/",
  "/jean-vanier-ai-giovani-2/": "/it/la-festa-continua/",
  "/perche-a-lourdes-2/": "/it/la-festa-continua/",
  "/lettera-di-presentazione-del-cardinale-hume-2/": "/it/la-festa-continua/",
  "/celebriamo-la-pasqua-1981-nella-comunita-fede-e-luce-2/": "/it/la-festa-continua/",
  "/perche-questo-insieme-speciale-2/": "/it/la-festa-continua/",
  "/1-insieme-in-cammino-siamo-tutti-pellegrini/": "/it/la-festa-continua/",
  "/2-pellegrini-in-comunita-2/": "/it/la-festa-continua/",
  "/3-in-comunita-accoglienti-2/": "/it/la-festa-continua/",
  "/4-ognuno-ha-il-suo-posto-nella-comunita-2/": "/it/la-festa-continua/",
  "/5-sono-loro-che-ci-uniscono-e-ci-guidano-2/": "/it/la-festa-continua/",
  "/6-cristo-risorto-fa-di-noi-un-solo-popolo-2/": "/it/la-festa-continua/",
  "/7-lo-spirito-santo-dono-di-gesu-risorto-2/": "/it/la-festa-continua/",
  "/8-nutrirsi-di-gesu-attraverso-la-parola-2/": "/it/la-festa-continua/",
  "/9-nella-preghiera-personale-2/": "/it/la-festa-continua/",
  "/11-compiendo-la-volonta-del-padre-2/": "/it/la-festa-continua/",
  "/10-nella-preghiera-comunitaria-2/": "/it/la-festa-continua/",
  "/12-con-i-santi-2/": "/it/la-festa-continua/",
  "/13-con-maria-2/": "/it/la-festa-continua/",
  "/14-nelleucarestia-venite-a-me-2/": "/it/la-festa-continua/",
  "/15-nelleucarestia-restate-in-me-2/": "/it/la-festa-continua/",
  "/16-il-perdono-2/": "/it/la-festa-continua/",
  "/fede-e-luce-domande-e-risposte-2/": "/it/la-festa-continua/",
  "/ma-di-sicuro-torna-il-sereno-2/": "/it/la-festa-continua/",
  "/fede-e-luce-pasquale-2/": "/it/la-festa-continua/",
  "/cosa-e-fede-e-luce-tre-risposte-2/": "/it/la-festa-continua/",
  "/ognuno-ha-il-suo-posto-nella-comunita-2/": "/it/la-festa-continua/",
  "/scegliere-di-lasciarsi-scegliere-2/": "/it/la-festa-continua/",
  "/il-posto-della-persona-handicappata-nelle-nostre-comunita-2/": "/it/la-festa-continua/",
  "/genitori-di-persone-con-disabilita-nessuno-disturba-nessuno-2/": "/it/la-festa-continua/",
  "/tre-tappe-nella-mia-vita-2/": "/it/la-festa-continua/",
  "/incontro-fra-genitori-2/": "/it/la-festa-continua/",
  "/lorganizazione-a-fede-e-luce/": "/it/lorganizzazione-a-fede-e-luce/",
  "/la-festa-continua-2/": "/it/lorganizzazione-a-fede-e-luce/",
  "/tu-sostieni-2/": "/it/18-domande-su-fede-e-luce/",
  "/i-fratelli-e-le-sorelle-di-persone-con-disabilita-2/": "/it/18-domande-su-fede-e-luce/",
  "/cosa-e-e-come-funziona-una-comunita-fede-e-luce-2/": "/it/18-domande-su-fede-e-luce/",
  "/prendete-e-mangiatene-tutti-2/": "/it/18-domande-su-fede-e-luce/",
  "/la-festa-a-fede-e-luce-2/": "/it/18-domande-su-fede-e-luce/",
  "/il-pellegrinaggio-a-fede-e-luce-2/": "/it/18-domande-su-fede-e-luce/",
  "/18-domande-su-fede-e-luce-2/": "/it/primo-campeggio-fede-e-luce/",
  "/animare-una-messa-e-renderla-viva-facendo-lunita-2/": "/it/principi-di-azione-per-una-equipe-di-animazione/",
  "/principi-di-azione-per-una-equipe-di-animazione-2/": "/it/dare-vita-movimento-calore-limportanza-dellanimazione-nelle-comunita-fede-e-luce/",
  "/dare-vita-movimento-calore-limportanza-dellanimazione-nelle-comunita-fede-e-luce-2/": "/it/dopo-di-me-il-diluvio-commedia-musicale-del-gruppo-fede-e-luce-di-san-paolo/",
  "/dopo-di-me-il-diluvio-commedia-musicale-del-gruppo-fede-e-luce-di-san-paolo-2/": "/it/la-festa-uno-dei-momenti-essenziale-della-comunita-fede-e-luce/",
  "/la-festa-uno-dei-momenti-essenziali-della-comunita-fede-e-luce/": "/it/unora-di-musica-con-suor-maria/",
  "/unora-di-musica-con-suor-maria-2/": "/it/comunita-di-fede-e-luce/",
  "/comunita-di-fede-e-luce-2/": "/it/consigli-di-lettura-insieme-n-29/",
  "/in-viaggio-verso-lourdes-2/": "/it/lourdes-1981-giovedi-santo/",
  "/lourdes-1981-giovedi-santo-2/": "/it/lourdes-1981-venerdi-santo/",
  "/lourdes-1981-venerdi-santo-2/": "/it/lourdes-1981-sabato-santo/",
  "/lourdes-1981-domenica-di-pasqua-2/": "/it/va-verso-i-tuoi-fratelli-e-di-loro/",
  "/va-verso-i-tuoi-fratelli-e-di-loro-2/": "/it/voci-dal-pellegrinaggio-lourdes-1981-frammenti-di-vita-e-di-fede/",
  "/voci-dal-pellegrinaggio-lourdes-1981-frammenti-di-vita-e-di-fede-2/": "/it/una-nuova-speranza/",
  "/una-nuova-speranza-2/": "/it/buon-natale-1981-e-un-numero-speciale/",
  "/buon-natale-1981-e-un-numero-speciale-2/": "/it/storia-di-natale/",
  "/storia-di-natale-2/": "/it/il-futuro-di-insieme-una-catena-che-diventa-sempre-piu-grande/",
  "/risorse-per-una-catechesi-sensoriale-e-inclusiva/": "/it/catechesi-inclusiva-materiali-tattili/",
  "/la-piccola-marcia/": "/it/alla-piccola-marcia-di-assisi/",
  "/il-ruolo-di-cura-tre-film-alla-berlinale-che-ispirano-una-riflessione/": "/it/il-ruolo-di-cura-quattro-film-berlinale/",
  "/il-cugino-che-sapeva-di-lavanda/": "/it/claudio-lavanda/",
  "/il-coraggio-di-cambiare-2/": "/it/suor-veronica-pompei/",
  "/se-sei-sola-invece-no/": "/it/se-sei-sola-invece-non-e-bello/",
  "/lourdes-a-miracle-of-encounter/": "/it/mother-teresa-of-calcutta-dedicated-to-children-and-to-all-of-us/",
  "/interactive-games-for-unforgettable-group-funmatica/": "/it/interactive-games-unforgettable-group-fun/",
  "/la-festa-di-compleanno-di-veronica-felice/": "/it/la-festa-di-compleanno-di-veronica/",

  // Fix-7 — 96 URL singoli aggiunti a redirects-legacy.json (2026-05-19) ma mai al Worker
  "/la-rivista/": "/it/archivio/",
  "/i-diari-di-ombre-e-luci/": "/it/rubriche/diari/",
  "/mariangela-bertolini/": "/it/focus/mariangela-bertolini/",
  "/author/nanni/": "/it/autori/nanni-bertolini/",
  "/chi-siamo/": "/it/chi-siamo/",
  "/chi-siamo/la-rivista/": "/it/chi-siamo/#la-rivista",
  "/chi-siamo/la-redazione/": "/it/chi-siamo/#la-redazione",
  "/chi-siamo/redazione-storica/": "/it/chi-siamo/#redazione-storica",
  "/chi-siamo/collaboratori/": "/it/chi-siamo/#collaboratori",
  "/chi-siamo/hanno-scritto-per-noi/": "/it/chi-siamo/#hanno-scritto-per-noi",
  "/chi-siamo/contatti/": "/it/chi-siamo/#contatti",
  "/dona/": "/it/sostienici/",
  "/contribuisci/": "/it/sostienici/",
  "/about/": "/it/chi-siamo/",
  "/autori/": "/it/autori/",
  "/categoria/": "/it/categoria/",
  "/cerca/": "/it/cerca/",
  "/diari/": "/it/diari/",
  "/rubriche/": "/it/rubriche/",
  "/tag/": "/it/tag/",
  "/blog/en/": "/en/",
  "/studiosi-educatori-e-attivisti-ombre-e-luci/": "/it/studiosi-educatori-attivisti/",
  "/studiosi-educatori-e-attivisti-ombre-e-luci": "/it/studiosi-educatori-attivisti/",
  "/contatti/": "/it/chi-siamo/",
  "/fede-e-luce/": "/it/categoria/fede-e-luce/",
  "/famiglia/": "/it/categoria/famiglia/",
  "/spiritualita/": "/it/categoria/spiritualita/",
  "/esperienze/": "/it/categoria/progetti/",
  "/catechesi/": "/it/categoria/spiritualita/",
  "/catechesi-e-disabilita/": "/it/categoria/spiritualita/",
  "/recensioni/": "/it/rubriche/recensioni/",
  "/recensioni/libri-recensioni/": "/it/rubriche/recensioni/",
  "/interviste/": "/it/rubriche/interviste/",
  "/editoriali/": "/it/rubriche/editoriali/",
  "/testimonianze/": "/it/rubriche/testimonianze/",
  "/riflessioni/": "/it/rubriche/testimonianze/",
  "/storia-ombre-e-luci/": "/it/chi-siamo/",
  "/storia-di-ombre-e-luci/": "/it/chi-siamo/",
  "/jean-vanier/": "/it/autori/jean-vanier/",
  "/jeanvanier/": "/it/autori/jean-vanier/",
  "/archivio/": "/it/archivio/",
  "/argomenti/": "/it/archivio/",
  "/articoli/": "/it/archivio/",
  "/archivi/": "/it/archivio/",
  "/attualita/": "/",
  "/tempo-libero/": "/it/categoria/tempo-libero/",
  "/vacanze/": "/it/categoria/tempo-libero/",
  "/scuola/": "/it/categoria/scuola/",
  "/lavoro/": "/it/categoria/lavoro/",
  "/sport/": "/it/categoria/sport/",
  "/medicina/": "/it/categoria/salute/",
  "/affettivita/": "/it/categoria/famiglia/",
  "/vita-in-autonomia/": "/it/archivio/",
  "/vita-comunitaria/": "/it/tag/vita-comunitaria/",
  "/vita-fede-e-luce/": "/it/categoria/fede-e-luce/",
  "/dopo-di-noi/": "/it/tag/dopo-di-noi/",
  "/scienza-e-vita/": "/it/categoria/salute/",
  "/cinema-e-disabilita/": "/it/focus/speciale-cinema-e-disabilita/",
  "/disabilita-e-massmedia/": "/it/categoria/cultura/",
  "/dedicato-ai-bambini/": "/it/categoria/famiglia/",
  "/istituzioni-e-disabilita/": "/it/archivio/",
  "/progetti/": "/it/categoria/progetti/",
  "/autismo/": "/it/focus/autismo/",
  "/autismo-cat/": "/it/focus/autismo/",
  "/podcast/": "/it/archivio/",
  "/video/": "/it/archivio/",
  "/news/": "/",
  "/spettacoli/": "/it/categoria/cultura/",
  "/aktiont4/": "/it/focus/aktion-t4-sterminio-persone-disabilita/",
  "/aktion-t4-sterminio-persone-disabilita/": "/it/focus/aktion-t4-sterminio-persone-disabilita/",
  "/numero-1-1983/": "/it/archivio/oel-1/",
  "/numero-2-1983/": "/it/archivio/oel-2/",
  "/numero-3-1983/": "/it/archivio/oel-3/",
  "/numero-4-1983/": "/it/archivio/oel-4/",
  "/ombre-e-luci-sfogliabile/": "/it/archivio/",
  "/insieme/insieme-giallo/": "/it/archivio/ins-32/",
  "/insieme/insieme-speciale-fede-e-luce/": "/it/archivio/ins-32/",
  "/en/n-31-en/": "/en/archive/ins-31/",
  "/en/n-92-en/": "/en/archive/oel-92/",
  "/en/n-100-en/": "/en/archive/oel-100/",
  "/en/n-151-en/": "/en/archive/oel-151/",
  "/en/n-156-en/": "/en/archive/oel-156/",
  "/en/n-160-en/": "/en/archive/oel-160/",
  "/en/n-170-en/": "/en/archive/oel-170/",
  "/en/testimonies/": "/en/sections/testimonies/",
  "/en/reviews/": "/en/sections/reviews/",
  "/en/editorials/": "/en/sections/editorials/",
  "/en/interviews/": "/en/sections/interviews/",
  "/en/experiences/": "/en/sections/testimonies/",
  "/en/reflections/": "/en/sections/testimonies/",
  "/en/faith-and-disability/": "/en/category/faith-and-light/",
  "/en/read-our-stories-in-english/": "/en/",
  "/en/home-english/": "/en/",
  "/en/project/": "/en/archive/",
  "/en/senza-categoria-en/": "/en/",
  "/newsletter/": "/it/newsletter/",
  "/archivio-newsletter/": "/it/newsletter/",
  "/iscrizione-newsletter-confermata/": "/it/newsletter/",
  "/sostienici/": "/it/sostienici/",
  "/sostienici-2019/": "/it/sostienici/",
  "/regala-ol/": "/it/sostienici/",
  "/creative-commons/": "/it/chi-siamo/",
  "/promo-natale-2017/": "/it/sostienici/",
  "/formazione-giovani/": "/it/chi-siamo/",
  "/home2022/": "/",
  "/il-blog-di-benedetta/": "/it/rubriche/diari/",
  "/ol-incontra/": "/it/archivio/",
  "/noi-papa/": "/it/archivio/",
  "/noi-papa-un-figlio-disabile/": "/it/archivio/",
  "/hisse-et-oh/": "/it/archivio/",
  "/ciao-stefano-di-franco/": "/it/autori/stefano-di-franco/",
  "/stefano/": "/it/autori/stefano-di-franco/",
  "/promocei/": "/it/archivio/",
  "/in-tutto-il-mondo-e-natale/": "/",
  "/order-confirmation/": "/it/sostienici/",
  "/order-failed/": "/it/sostienici/",
  "/1974/": "/it/archivio/",
  "/1975/": "/it/archivio/",
  "/n-47-2/": "/it/archivio/oel-47/"
};

// ── WordPress proxy ────────────────────────────────────────────────────────
// Il sito WordPress originale è su Aruba (89.46.105.36). Da quando il DNS è
// passato a Cloudflare Pages, /wp-admin e le route WP non sono più raggiungibili.
// Questo proxy le reinstrada trasparentemente verso l'IP Aruba.
const WP_PREFIX = ['/wp-admin', '/wp-content', '/wp-includes', '/wp-json', '/feed'];
const WP_EXACT  = ['/wp-login.php', '/wp-cron.php', '/xmlrpc.php'];
const ARUBA_IP  = '89.46.105.36';
const WP_HOST   = 'www.ombreeluci.it';

const DEFAULT_PAGES_ORIGIN = 'https://ombreeluci-staging.pages.dev';

function isWordPressPath(path) {
  if (WP_EXACT.includes(path)) return true;
  return WP_PREFIX.some(p => path === p || path.startsWith(p + '/'));
}

/** Upstream Astro su Cloudflare Pages. env.PAGES_ORIGIN da wrangler.toml [vars]. */
function pagesBaseUrl(env) {
  const raw = env?.PAGES_ORIGIN || DEFAULT_PAGES_ORIGIN;
  return String(raw).replace(/\/$/, '');
}

/**
 * Inoltra al progetto Pages. NON usare fetch(request) sullo stesso host: il DNS
 * risolve ancora verso Aruba e riceveresti WordPress / risposte sbagliate.
 */
async function forwardToPages(request, env) {
  const url = new URL(request.url);
  const target = new URL(url.pathname + url.search, pagesBaseUrl(env));

  const headers = new Headers(request.headers);
  headers.delete('cf-connecting-ip');
  // Segnala all'app Astro che la richiesta arriva dal Worker (proxy legittimo verso ombreeluci.it),
  // non da un accesso diretto a *.pages.dev (es. Googlebot che indicizza il backend nudo).
  headers.set('X-Internal-Proxy-Auth', env.INTERNAL_PROXY_AUTH);
  // Altrimenti il client manda Host: ombreeluci.it e la subrequest verso *.pages.dev fallisce o va storta.
  headers.delete('Host');

  return fetch(
    new Request(target.toString(), {
      method: request.method,
      headers,
      body: ['GET', 'HEAD'].includes(request.method) ? undefined : request.body,
      // Senza questo, fetch() segue in automatico un eventuale 301 di Pages: la subrequest
      // risultante punterebbe a ombreeluci.it (stessa zona del Worker), Cloudflare la instrada
      // fuori dal Worker per prevenire loop, e finisce su un origin senza certificato → 526.
      // Con 'manual', il 301 arriva qui come Response normale (Location già assoluto verso
      // ombreeluci.it, impostato dal middleware) e va solo inoltrato al client com'è.
      redirect: 'manual',
    })
  );
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = url.pathname;

    // WordPress proxy — route WP → Aruba; tutto il resto (es. /api/revalidate) → forwardToPages
    if (isWordPressPath(path)) {
      const target = new URL(request.url);
      target.hostname = ARUBA_IP;
      target.protocol = 'http:';
      target.port = '80';

      const headers = new Headers(request.headers);
      headers.set('Host', WP_HOST);
      // Rimuovi header CF che potrebbero disturbare WP
      headers.delete('cf-connecting-ip');

      const proxyReq = new Request(target.toString(), {
        method:  request.method,
        headers,
        body:    ['GET', 'HEAD'].includes(request.method) ? undefined : request.body,
        redirect: 'manual',
      });

      return fetch(proxyReq);
    }

    // Rule C+D: lookup table (exact match); decodedPath copre chiavi Unicode (es. /メリークリスマス/)
    const decodedPath = (() => { try { return decodeURIComponent(path); } catch (_) { return path; } })();
    const cdTarget = REDIRECTS[path] || REDIRECTS[decodedPath];
    if (cdTarget) {
      return Response.redirect('https://ombreeluci.it' + cdTarget, 301);
    }

    // Rule B: /YYYY/MM/DD/slug/ → /slug/
    const dateMatch = path.match(/^\/\d{4}\/\d{2}\/\d{2}\/(.+)$/);
    if (dateMatch) {
      return Response.redirect('https://ombreeluci.it/it/' + dateMatch[1], 301);
    }

    // Rule E: /page/N/ → archivio (vecchie pagine WP paginate)
    if (/^\/page\/\d+\/?$/.test(path)) {
      return Response.redirect('https://ombreeluci.it/it/archivio/', 301);
    }

    // Rule F: /YYYY/slug/ → /it/slug/ (permalink WP anno-only, senza mese/giorno)
    const yearSlugMatch = path.match(/^\/(\d{4})\/([^/]+?)\/?$/);
    if (yearSlugMatch) {
      return Response.redirect('https://ombreeluci.it/it/' + yearSlugMatch[2] + '/', 301);
    }

    // Rule F2: /en/YYYY/slug/ → /en/slug/ (EN articles WP con anno nel permalink)
    const enYearSlugMatch = path.match(/^\/en\/(\d{4})\/([^/]+?)\/?$/);
    if (enYearSlugMatch) {
      return Response.redirect('https://ombreeluci.it/en/' + enYearSlugMatch[2] + '/', 301);
    }

    // Rule G: /n-N/ → /it/archivio/oel-N/ (shortlink numeri rivista)
    const nMatch = path.match(/^\/n-(\d+)\/?$/);
    if (nMatch) {
      return Response.redirect('https://ombreeluci.it/it/archivio/oel-' + nMatch[1] + '/', 301);
    }

    // Rule H: /project/numero-N-*/ → /it/archivio/oel-N/
    const projectNumeroMatch = path.match(/^\/project\/numero-(\d+)-/);
    if (projectNumeroMatch) {
      return Response.redirect('https://ombreeluci.it/it/archivio/oel-' + projectNumeroMatch[1] + '/', 301);
    }

    // Rule I: /project/*/ o /project_category/*/ → archivio
    if (/^\/project[\/_]/.test(path) || path.startsWith('/project/')) {
      return Response.redirect('https://ombreeluci.it/it/archivio/', 301);
    }

    // Rule J: /author/slug/ → /it/autori/slug/
    const authorMatch = path.match(/^\/author\/([^/]+)\/?$/);
    if (authorMatch) {
      return Response.redirect('https://ombreeluci.it/it/autori/' + authorMatch[1] + '/', 301);
    }

    // Rule K: /diario-di-*/ → /it/diari/diario-di-*/
    const diarioMatch = path.match(/^(\/diario-di-[^/]+)\/?$/);
    if (diarioMatch) {
      return Response.redirect('https://ombreeluci.it/it/diari' + diarioMatch[1] + '/', 301);
    }

    // Rule L: /insieme/insieme-n-N/ → /it/archivio/ins-N/
    const insiemeMatch = path.match(/^\/insieme\/insieme-n-(\d+)\/?$/);
    if (insiemeMatch) {
      return Response.redirect('https://ombreeluci.it/it/archivio/ins-' + insiemeMatch[1] + '/', 301);
    }

    // Rule M: /archivio/oel-N/ o /archivio/ins-N/ → /it/archivio/oel-N| ins-N/
    const archivioIssueMatch = path.match(/^\/archivio\/((?:oel|ins)-\d+)\/?$/);
    if (archivioIssueMatch) {
      return Response.redirect('https://ombreeluci.it/it/archivio/' + archivioIssueMatch[1] + '/', 301);
    }

    // Rule N: /autori/slug/ → /it/autori/slug/
    const autoriMatch = path.match(/^\/autori\/([^/]+)\/?$/);
    if (autoriMatch) {
      return Response.redirect('https://ombreeluci.it/it/autori/' + autoriMatch[1] + '/', 301);
    }

    // Rule O: /blog/slug-en/ → /en/slug/ (legacy WP EN con suffisso -en)
    const blogEnMatch = path.match(/^\/blog\/([^/]+)-en\/?$/);
    if (blogEnMatch) {
      return Response.redirect('https://ombreeluci.it/en/' + blogEnMatch[1] + '/', 301);
    }

    // Rule P: /blog/slug/ → /it/slug/ (legacy WP IT)
    const blogItMatch = path.match(/^\/blog\/([^/]+?)\/?$/);
    if (blogItMatch) {
      return Response.redirect('https://ombreeluci.it/it/' + blogItMatch[1] + '/', 301);
    }

    // Rule Q0: /categoria/catechesi → spiritualità (migrazione 2026-05)
    if (path === '/categoria/catechesi' || path === '/categoria/catechesi/') {
      return Response.redirect(url.origin + '/it/categoria/spiritualita/', 301);
    }

    // Rule Q: /categoria/slug/ → /it/categoria/slug/
    const categoriaMatch = path.match(/^\/categoria\/([^/]+)\/?$/);
    if (categoriaMatch) {
      return Response.redirect('https://ombreeluci.it/it/categoria/' + categoriaMatch[1] + '/', 301);
    }

    // Rule R: /it/* e /en/* senza trailing slash → 301 con slash (canonical SEO)
    // Gestito qui perché forwardToPages() segue i redirect interni di Astro silenziosamente.
    if (
      !path.endsWith('/') &&
      !path.includes('.') &&
      !path.startsWith('/api/') &&
      (path.startsWith('/it/') || path.startsWith('/en/'))
    ) {
      return Response.redirect(url.origin + path + '/', 301);
    }

    // Tutto il resto → Astro su CF Pages.
    return forwardToPages(request, env);
  }
};
